Financial-Times/up-service-files

services.yaml
Waiting on PR
https://github.com/Financial-Times/coco-fleet-deployer/pull/2
=> Removing global count from service definition

service-files/aggregate-healthcheck-sidekick@.service
it was just the same as the others after all.
=> remove reference to elb

service-files/vulcan-elb-presence.service
https://github.com/Financial-Times/coco-provisioner/pull/15
=> Use the cluster specific elb

service-files/aggregate-healthcheck@.service
https://github.com/Financial-Times/coco-aggregate-healthcheck/pull/6
=> Remove exclude list and update key prefix

service-files/methode-image-binary-transformer-sidekick@.service
Split out healthchecks to be per instance
=> Single instance per service hc

service-files/aggregate-healthcheck-sidekick@.service
Can get rid of the rewrite rule and is more inline with the standard
=> Changed to __health

service-files/deployer.service, service-files/deployer.timer, services.yaml
https://github.com/Financial-Times/coco-fleet-deployer/pull/8
=> Switch deployer to run on a timer

services.yaml
This version contains enhanced logging & monitoring, also eom file fix to reduce noise in the logs.
=> Bump synth-img-pub version

service-files/image-cleaner.service, service-files/image-cleaner.timer, services.yaml
https://github.com/Financial-Times/coco-docker-gc
=> Stolen docker-gc from shopify, had to change a bit to make it work

service-files/splunk-forwarder.service
pretty simple change although not tested yet.
=> pass environment when calling the filter

service-files/diamond.service, service-files/splunk-forwarder.service
Seperate metrics per environment
=> Seperate metrics based on env tag

service-files/vulcan.service
We aren't actively debugging it now but it spams splunk a fair bit
=> Stop vulcan logging at INFO

service-files/image-cleaner.service
Effort for the service healthcheck
=> Image-cleaner service to remain running after exiting

service-files/zookeeper.service
=> specify that zookeeper-should-nudge-kafka-on-startup

service-files/elasticsearch-sidekick@.service, service-files/elasticsearch@.service, service-files/kibana-sidekick@.service, service-files/kibana@.service
For experimentation only. No HA, atypical sidekick behaviour, etc.
=> Initial version of ES and Kibana service files.

service-files/restorage-es-sidekick@.service, service-files/restorage-es@.service
Unit files only. Not enabled yet.
=> Initial version of restorage backed by ES

vulcan.service
Comes bundled with session auth plugin
=> Switch vulcan service to FT build of vulcan

nativerw-sidekick@.service
tested in my own cluster. ready for pre-prod at least I think,
=> Convert native rw to vcb

kafka.service, zookeeper.service
Persist zk and kafka data through host VM restarts
=> Mount zk and kafka on the host

kafka.service, methode-content-importer@.service, services.yaml, zookeeper.service
* using latest version with suppporting wordpress content
* fixed service file
+ changes for ZK and Kafka to persist data
=> Updated version of (Methode) Content Importer

diamond.service
Finally managed to make it work in pre-prod, tested and already working on Grafana for pre-prod.
http://grafana.ft.com/dashboard/db/coco
select pre-prod in the dropdown
=> System health metrics to Graphite with short prefix like: ip-172-24-75-233

document-store-api-sidekick@.service, document-store-api@.service, services.yaml
- incremental release to prod of dynpub-uk cluster
=>  added prod version of DSAPI and corrected service files

methode-article-transformer-sidekick@.service, methode-article-transformer@.service, services.yaml
Corresponding version in UCS prod is #185, git commit id: f81d426874343e3ce05c1a9f2e7c4a5dc0c8ee1b, artifact id: 0.1.185
=> added prod version of MAT and related service files

cms-notifier-sidekick@.service
This reverts commit dde4d4b364805ec4dad8ca76b34f43e852a7874c.
=> Revert "Using vulcan config builder for cms-notifier"

services.yaml
LastModified date is added to methode-article-transformer and to methode-list-transformer.
=> Update article-transformer to v32 and list transformer to v9.

services.yaml
* Fix methode-list-transformer versioning.
* Add lastModified to methode-list-transformer (v9)
* Add lastModified to methode-article-transformer (v32)
=> Merge pre-prod to prod

services.yaml
Also, for document store api, bump version and ensure there are 2
instances.
=> Zero-downtime deployment for document and notification stores.

services.yaml
This reverts commit 8e826263fdfa6e87b75ca481545cb72a210316a2, reversing
changes made to 5c5ee3c35e92e7942a353263689971b1ae4eb385.
=> Revert "Merge pull request #218 from Financial-Times/bump-wpat-version"

format_services_yaml.go
added this "script" inline for now. if people prefer to move it elsewhere I'm fine with that.
=> "script" to sort the services file

format_services_yaml.go
=> Sorted services

services.yaml, varnish@.service
=> Added varnish to services. Use varnish with docker image version

enriched-content-read-api-sidekick@.service, enriched-content-read-api@.service, services.yaml
* switched Enriched Content Read API to VCB config
* updated service files to latest conventions
* added app to services.yaml
* this isn't expected to run/be merged, just a trial version
=> Updated enriched content read API services files

neo4j-sidekick@.service, neo4j@.service
neo services (hand copied from elasticSearch branch)
NOT USED (yet)
=> neo services

neo4j-sidekick@.service
=> Adding some headers to neo4j frontend

services.yaml, wordpress-article-transformer@.service
Do not merge yet!
Edit: have to increment also the version number.
=> Wat update

api-policy-component-sidekick@.service, api-policy-component@.service, document-store-api-sidekick@.service, enriched-content-read-api-sidekick@.service, notifications-rw-sidekick@.service, services.yaml
=> Containerize api-policy-component

document-store-api-sidekick@.service, services.yaml, varnish-sidekick@.service
Finally we managed to setup varnish as default entry point for requests in xp
=> Setup varnish for caching requests going to content and lists endpoints

services.yaml
Adding timestamps to notifications
=> Bump versions - UPP-1072

elb-dns-registrator.service, services.yaml
=> Versioning elb-dns-registrator v1.0.0

varnish-sidekick@.service
Yeah, I know, I should have tested it with the recent changes too....
=> Fixing varnish's Host regex

services.yaml
Skip checking live content from notifications endpoint
=> Bump PAM version

tunnel-registrator.service
Do a DELETE, disregard the result. Check there is no record (404)
followed by a create.
=> Fix konstructor calls

methode-image-model-transformer@.service, services.yaml
* Addig whiteListRegex for binary-ingester to avoid processing non-images (binary-ingester v82)
* Fixing externalBinaryUrl for image models (methode-image-model-transformer v42)
=> Fixing image-related configurations.

services.yaml
Trying to fix PAM false alarms.
=> Reduce CMS notifiers number from 2 to 1

services.yaml
Tested the changes in MAT to accept the POST requests with payload for the article-preview.
=> Updated the version of the Methode-Article-Transformer to accept POST

services.yaml
=> Updated the version of MAT to accept POST with payload

services.yaml, vulcan.service
Additional changes from pre-prod:
* Updated the version of the Methode-Article-Transformer to accept POST with payload
=> Versioning vulcan

services.yaml, synthetic-image-publication-monitor-aws@.service, synthetic-image-publication-monitor-coco@.service
New version with `exec` that fixes orphaned containers
New pull format to stop pull requests when image is present
Moved the images to dockerhub
=> New SIPM service

services.yaml, v2-annotations-rw-sidekick@.service, v2-annotations-rw@.service, v2-content-annotator-sidekick@.service, v2-content-annotator@.service
=> Add v2 annotator for pre prod

content-public-read-preview@.service
The content-public-read-preview service file contains the script to set the API host configuration according to the environment in which the service is running.
=> Additionally improved content-public-read-preview service file

services.yaml, v2-annotations-rw-sidekick@.service, v2-content-annotator-sidekick@.service
Update content-annotator and annotations-rw.
=> Add v2 annotator

notifications-ingester@.service
notiification-ingester version of https://github.com/Financial-Times/up-service-files/pull/360
=> Versioning notification-ingester

api-policy-component@.service, services.yaml
=> Add graphite reporter for apc

binary-ingester-sidekick@.service, binary-writer-sidekick@.service
Forgot 2 ports from https://github.com/Financial-Times/up-service-files/pull/362
=> Optimizing 2 more port settings

services.yaml
- added predicate to generated suggestion
- tested in XP:
```
{
"uuid": "ea8f0ade-d166-11e5-a8b7-de8b0bc6a49a",
"suggestions": [{
"thing": {
"id": "9b91f46a-bbd4-36d0-be14-8035faa7e82d",
"prefLabel": "Economic News",
"predicate": "isClassifiedBy",
"types": ["http://www.ft.com/ontology/thing/Subject"]
},
"provenances": [{
"scores": [{
"scoringSystem": "http://api.ft.com/scoringsystem/FT-RELEVANCE-SYSTEM",
"value": 1
},
{
"scoringSystem": "http://api.ft.com/scoringsystem/FT-CONFIDENCE-SYSTEM",
"value": 1
}]
}]
}
```
=> Upgrading v1-suggestor to v0.0.4

services.yaml, v1-annotations-rw-sidekick@.service, v1-annotations-rw@.service, v1-content-annotator-sidekick@.service, v1-content-annotator@.service
The same PR as : https://github.com/Financial-Times/up-service-files/pull/366 - after solving the merge conflicts.
=> Containerize v1 annotations-rw

services.yaml
* https://github.com/Financial-Times/v1-suggestor/pull/8
* https://github.com/Financial-Times/v1-suggestor/pull/9
* https://github.com/Financial-Times/v1-suggestor/pull/10
* tested in XP, works
=> Bumping v1-suggestor to v0.0.5

public-annotations-api-sidekick@.service, public-annotations-api@.service, services.yaml
I will complete the PR with the version number in the service file, as soon as my changes get merged in master. 
Otherwise, it's ready and tested in XP.
=> Containerize public-annotations-api

genres-rw-neo4j-sidekick@.service, genres-rw-neo4j@.service, services.yaml
* tried in XP, read and write working
* also check out https://github.com/Financial-Times/genres-rw-neo4j, adapted from the subjects counterpart
=> Adding genres-rw-neo4j

services.yaml
* tested in XP, works
* also see https://github.com/Financial-Times/v1-suggestor/pull/11
=> Bumping v1-suggestor to v0.0.6

publish-availability-monitor@.service
=> start sidekick along pam

content-public-read-preview-sidekick@.service, services.yaml, varnish-sidekick@.service
Tested in ad-hoc cluster + xp.
Note: update auth keys before deployment. 
Edit: deployed and tested in pre-prod.
=> Up read auth

services.yaml
http://git.svc.ft.com:8080/projects/CP/repos/content-annotator/pull-requests/10/overview
and
http://git.svc.ft.com:8080/projects/CP/repos/content-annotator/pull-requests/7/overview
=> Upped the version of the content annotator to 22

services.yaml
Gets the transformed payload and then adds it to the kafka message on CmsPublicationEvents
=> Payload on kafka

cms-notifier-sidekick@.service, content-public-read-preview-sidekick@.service, elb-presence@.service, services.yaml, varnish-sidekick@.service, varnish@.service
Tie elb-presence to the varnish instances
=> Update varnish to be the entrypoint of the cluster

services.yaml
https://github.com/Financial-Times/nativerw/pull/8
https://github.com/Financial-Times/nativerw/pull/9
* tried in XP, new `__ids` endpoint works
=> Bump nativerw to v40

services.yaml, up-queue-sender-v1-metadata-sidekick@.service, up-queue-sender-v1-metadata@.service
=> Add up queue sender

notifications-push-sidekick@.service, services.yaml, varnish@.service
i had no luck (or i had luck) and 33000 clashed immediately in prod-uk with an already running container
=> Fix for port clash.

services.yaml
=> Bumping nativerw v41 - no app changes

services.yaml
Changes since 0.0.8:
* https://github.com/Financial-Times/v1-suggestor/pull/14
* https://github.com/Financial-Times/v1-suggestor/pull/16 - tried in XP
=> Bump v1-suggestor to 0.0.10

services.yaml
&& fixes in public-annotations-api. See release history: https://github.com/Financial-Times/public-annotations-api/releases
=> Read side support of tagging with locations and genres 

services.yaml
Adds routing rules for content-by-contept apps
=> New varnish

services.yaml
https://jira.ft.com/browse/NFT-365
=> Standout flags

services.yaml
See https://github.com/Financial-Times/public-annotations-api/releases/tag/0.0.11
=> Updating public-annotations-api 

services.yaml
Now monitors the coreos version
https://github.com/Financial-Times/coco-system-healthcheck/releases/tag/1.0.1
=> New versio of sys-hc

services.yaml
Upgraded Content Preview to Version 0.0.4.
=> Dockerhub test

services.yaml
Changes:
- http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/14/overview
- http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/15/overview
=> Release varnish v61

services.yaml
Updating the WPAT version with feature image support.
=> Wpat with featured images

services.yaml
Increase malloc to 1024M:
http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/16/overview
=> Release varnish 62

services.yaml
mostly to pick up changes in the neo-model-utils-go library (required for the FTP2 deploys). Took the opportunity to update README files etc
=> Minor changes to all these services

services.yaml
http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/17/overview
=> Disable crawling

services.yaml
https://github.com/Financial-Times/vulcan-config-builder/pull/11
=> Vulcan-config-builder v1.1.0. Configured failover predicates for frontends

services.yaml
=> Update kafka-bridge: fix uuid validation remove, add connection re-use.

services.yaml
https://github.com/Financial-Times/notifications-push/pull/16
Edit: ehh, sorry about the misleading commit msg, it is notifications-push
=> bump notifications-push version

cms-metadata-kafka-bridge-sidekick@.service, content-ingester-neo4j-blue-sidekick@.service, content-ingester-neo4j-red-sidekick@.service, content-rw-neo4j-blue-sidekick@.service, content-rw-neo4j-red-sidekick@.service, v1-annotations-rw-blue-sidekick@.service, v1-annotations-rw-red-sidekick@.service, v1-content-annotator-blue-sidekick@.service, v1-content-annotator-red-sidekick@.service, v1-suggestor-sidekick@.service
=> Making sure backends don't expire for v1 annotations publish pipeline

services.yaml
Now a system critical service we want to ensure high % uptime
=> HA for aggregator-healthcheck

services.yaml
- see https://github.com/Financial-Times/v1-suggestor/pull/18
- tested in XP, works
=> Remove UTF8 hack in v1-suggestor

services.yaml
=> Bump content-importer version.

cms-kafka-bridge-prod-sidekick@.service, cms-kafka-bridge-prod@.service, cms-metadata-kafka-bridge-prod-sidekick@.service, cms-metadata-kafka-bridge-prod@.service, concept-suggestions-kafka-bridge-prod-sidekick@.service, concept-suggestions-kafka-bridge-prod@.service, services.yaml
- same changes as in XP, made separate branches as these are branch-specific and won't be merged back to master
=> Adding prod bridges

services.yaml
http://git.svc.ft.com/projects/CP/repos/notifications-rw/pull-requests/34/overview
=> bump notifications-rw

cms-notifier@.service, services.yaml
- see http://git.svc.ft.com/projects/CP/repos/cms-notifier/pull-requests/12/overview
- tested in XP, works
=> Parameterize cms-notifier with topic name

genres-rw-neo4j-blue-sidekick@.service, genres-rw-neo4j-red-sidekick@.service, locations-rw-neo4j-blue-sidekick@.service, locations-rw-neo4j-red-sidekick@.service, locations-transformer-sidekick@.service, memberships-rw-neo4j-blue-sidekick@.service, memberships-rw-neo4j-red-sidekick@.service, organisations-rw-neo4j-blue-sidekick@.service, organisations-rw-neo4j-red-sidekick@.service, people-rw-neo4j-blue-sidekick@.service, people-rw-neo4j-red-sidekick@.service, restorage-mongo-sidekick@.service, roles-rw-neo4j-blue-sidekick@.service, roles-rw-neo4j-red-sidekick@.service, sections-rw-neo4j-blue-sidekick@.service, sections-rw-neo4j-red-sidekick@.service, sections-transformer-sidekick@.service, subjects-rw-neo4j-blue-sidekick@.service, subjects-rw-neo4j-red-sidekick@.service, subjects-transformer-sidekick@.service, topics-rw-neo4j-blue-sidekick@.service, topics-rw-neo4j-red-sidekick@.service, topics-transformer-sidekick@.service, up-queue-sender-v1-metadata-sidekick@.service
=> Instance data

services.yaml, vulcan.service
=> Release new version of vulcan

services.yaml
change to prevent publish of blank body tags post transformation e.g. <body>  \n\n <body>
=> mat reject blank body

services.yaml, varnish@.service
http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/19/overview
Deployed to `xp` - Thu 19 May 10:32:15 BST 2016
Deployed to `pre-prod` - Thu 19 May 11:00:49 BST 2016
=> Updated config

content-ingester@.service, services.yaml, video-mapper-sidekick@.service, video-mapper@.service
=> Introducing video-mapper and its dependencies to the stack.

services.yaml
https://github.com/Financial-Times/vulcan-config-builder/pull/14
Deployed to `xp` - Thu 19 May 14:31:57 BST 2016
Deployed to `pre-prod` - Thu 19 May 14:32:32 BST 2016
=> New version of vcb

services.yaml, vulcan-config-builder.service
Deployed:
|Environment | Date                                               |
|-----------------|--------------------------------------------|
|xp                 |  Mon 23 May 20:59:38 BST 2016  |
|pre-prod       | Tue 24 May 09:34:37 BST 2016    |
=> Deploy https://github.com/Financial-Times/vulcan-config-builder/pull/16

services.yaml
https://github.com/Financial-Times/notifications-push/pull/19
https://github.com/Financial-Times/notifications-push/releases/tag/v2.1.1
Tested in xp, pre-prod.
=> fix for notifications-push msg parsing

synthetic-image-publication-monitor-aws@.service, synthetic-image-publication-monitor-coco@.service
=> Synth pub mon: remove redundant params

notifications-push@.service, services.yaml
https://github.com/Financial-Times/notifications-push/pull/20
Tested in:
* xp
* pre-prod
=> Push api consume fix

cms-kafka-bridge-pub-prod-sidekick@.service, cms-kafka-bridge-pub-prod@.service, cms-metadata-kafka-bridge-pub-prod-sidekick@.service, cms-metadata-kafka-bridge-pub-prod@.service, concepts-kafka-bridge-pub-prod-sidekick@.service, concepts-kafka-bridge-pub-prod@.service, services.yaml
=> Pub cluster bridge

services.yaml
0.18.3: https://github.com/Financial-Times/publish-availability-monitor/pull/74
0.18.4: https://github.com/Financial-Times/publish-availability-monitor/pull/75
Tested in xp, pre-prod. 
> Jun 08 14:24:26 ip-172-24-99-92.eu-west-1.compute.internal bash[13276]: INFO  - 2016/06/08 14:24:26.420813 methodeContent.go:230: External validation for content uuid=[5c8c7e2e-d715-11e5-829b-8564e7528e54] received statusCode: [500]
Jun 08 14:24:26 ip-172-24-99-92.eu-west-1.compute.internal bash[13276]: INFO  - 2016/06/08 14:24:26.420877 methodeContent.go:236: External validation for content uuid=[5c8c7e2e-d715-11e5-829b-8564e7528e54] received response body: [{"message":"server error"}]
Jun 08 14:24:26 ip-172-24-99-92.eu-west-1.compute.internal bash[13276]: INFO  - 2016/06/08 14:24:26.420895 app.go:181: …
=> Empty transformed article body fix

services.yaml
Changes include for the topics-rw-neo4j:
* Make all the alternative ids Identifier nodes
* Only use prefLabel
* Add build-info
* Update the RW for the new json model - coming out from the transformer
=> Topics-rw - adding identifier nodes

services.yaml
tested in XP
pre-prod is currently not fit for testing this.
=> Videos in articles

elb-dns-registrator.service, services.yaml, tunnel-registrator.service
Provisioner PR for new Konstructor API key https://github.com/Financial-Times/coco-provisioner/pull/111
Deployed:
| env | date |
|-------|---------|
|`xp`| Fri 10 Jun 11:01:58 BST 2016 |
|`pre-prod` | Fri 10 Jun 11:44:52 BST 2016 |
=> Use konstrctor api v2

services.yaml
http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/21/overview
Deployed
| env | date | verified | 
|-------|------|------------|
|semantic | Fri Jun 10 11:27:17 2016 +0100 | [x] |
|xp | Fri 10 Jun 15:42:05 BST 2016 | [x] |
|dynpub | Fri 10 Jun 15:43:07 BST 2016 | [x] | 
|pre-prod| Fri 10 Jun 15:44:07 BST 2016 | [x] |
=> Release v69

content-public-read-preview@.service, content-public-read-sidekick@.service, content-public-read@.service, services.yaml
deploying new instance of CPR to coco
=> Cpr to validate links

document-store-api-sidekick@.service, services.yaml
enriched content to passthrough validate linked resources parameter to downstream
=> Enriched content passthrough again

services.yaml
API policy component to add validatelinkedresources=true parameter
=> Bumping api policy component to v40

sections-transformer@.service, services.yaml
* Add build-info
* Use prefLabel and remove canonical name
* All identifiers moved to using the new approach (see example above)
* Add healthcheck
* Connect to TME directly not via structure service
=> Identifiers in sections transformer

services.yaml
Changes include for the sections-rw-neo4j:
* Make all the alternative ids Identifier nodes
* Only use prefLabel
* Add build-info
* Update the RW for the new json model - coming out from the transformer
=> Sections rw add identifiers

services.yaml
=> Update special-reports-rw to v1.1.0

services.yaml
=> Subjects rw add identifiers

services.yaml
=> Topics rw remove unused ids

services.yaml
http://git.svc.ft.com/projects/CP/repos/methode-list-transformer/pull-requests/37/overview
Video part was tested only locally (no video dummy stories exist in Test Methode)
Regression testing was done in pre-prod (lists w articles, blogs).
CC-ed some people recently working on MLT. Please tell if you're fine with us going to prod with this.
@sjwells @yolandeleungFT @peteclark-ft @izzyblues
=> Videos in lists

services.yaml
fix: http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/17/overview
Tested in xp & pre-prod.
=> bump CPR - expose standout section

concepts-kafka-bridge-pub-pre-prod@.service, concepts-kafka-bridge-pub-prod@.service, services.yaml
* I made a branch for each env since prod doesn't have pre-prod bridges, for example, and some bridges were updates manually straight on the env branch
* tried this in lower envs
* you need to destroy the number 2 nodes manually after the merge
=> concepts bridges - enable autocommit, set instance number to 1

public-content-by-concept-api-sidekick@.service
=> public-content-by-concept-sidekick to look the new way

concepts-kafka-bridge-pub-prod@.service, services.yaml
same changes as this: https://github.com/Financial-Times/up-service-files/pull/621 for prod
=> concepts bridge - enable autocommit, set instance number to 1

services.yaml
=> notifications-push v2.4.0 has the same format as UP notifications

notifications-ingester@.service, services.yaml
Do not merge yet. A few service versions still have to be incremented.
Tested in xp.
=> Store video notifications

cms-kafka-bridge-ucs-test@.service, cms-metadata-kafka-bridge-ucs-test@.service, concept-suggestions-kafka-bridge-ucs-test@.service, services.yaml
* pre-prod version of https://github.com/Financial-Times/up-service-files/commit/5b1c2b0aa9e22bb4368d83413c701c818c4a9449, goes together with https://github.com/Financial-Times/up-service-files/pull/631
=> Update pre-prod-specific bridges, add certs to their containers

services.yaml
=> Remove all v1 relationships at delete (not only MENTIONS relationships)

notifications-rw-sidekick@.service
=> notifications-rw: backendId fix

notifications-push-sidekick@.service, notifications-push@.service, services.yaml
=> notifications-push monitored by PAM

kafka-rest-proxy-sidekick.service
=> Improving kafka proxy sk port setting mechanism

cms-kafka-bridge@.service, cms-metadata-kafka-bridge@.service, concept-suggestions-kafka-bridge@.service, services.yaml
* https://github.com/Financial-Times/coco-kafka-bridge/pull/28
* tested in xp, looks good
=> Update bridges, add certs to bridge containers

cms-kafka-bridge@.service, cms-metadata-kafka-bridge@.service, concept-suggestions-kafka-bridge@.service
=> Removing vulcan auth params

services.yaml, splunk-forwarder.service
=> notifications-push v2.4.15, pam 0.19.0, logfilter 1.0.3

services.yaml
Fixes gtg error that could result in null pointer exception
=> bumped version

services.yaml
=> Add identifiers brands-rw

services.yaml
Fixed issue with un-closed connections in concept-ingester.
https://github.com/Financial-Times/concept-ingester/pull/10
=> bumped version from v1.1.0 to v1.1.1

services.yaml
=> Add identifiers roles-rw

services.yaml
Fixing issue with leftover containers
Tested in xp, looks good
=> Updating CPR version to v46

notifications-rw@.service, services.yaml
Api host is now cluster specific for notifications-rw
Notifications-rw v48 - encoding url params for links href
=> Api host is now cluster specific for notifications-rw

services.yaml
https://github.com/Financial-Times/publish-availability-monitor/pull/79
Tested in
* xp
* pre-prod
=> bump pam: WP content struct improvement

services.yaml
Tested successfully in xp and pre-prod
=> Expose-push-api-to-b2b

services.yaml
Merges changes from here -> https://github.com/Financial-Times/concept-ingester/pull/7
=> bumped version to 1.1.5 which added unit tests

aggregate-healthcheck-sidekick@.service, content-public-read-preview@.service, content-public-read@.service, neo4j-blue@.service, neo4j-red@.service, services.yaml
Content Public Read doesn't require 'Cache-Control: no-store' being set, whereas Content Public Preview does.
=> Adding environment variable for cache filtering

api-policy-component-sidekick@.service, api-policy-component@.service, content-preview-sidekick@.service, content-preview@.service, content-public-read-preview-sidekick@.service, content-public-read-preview@.service, content-public-read-sidekick@.service, content-public-read@.service, document-store-api-sidekick@.service, document-store-api@.service, enriched-content-read-api-sidekick@.service, enriched-content-read-api@.service, methodeapi-endpoint.service, public-annotations-api-sidekick@.service, public-annotations-api@.service, public-brands-api-sidekick@.service, public-brands-api@.service, public-concordances-api-sidekick@.service, public-concordances-api@.service, public-content-by-concept-api-sidekick@.service, public-content-by-concept-api@.service, public-organisations-api-sidekick@.service, public-organisations-api@.service, public-people-api-sidekick@.service, public-people-api@.service, public-six-degrees-sidekick@.service, public-six-degrees@.service, public-things-api-sidekick@.service, public-things-api@.service, services.yaml
Also fixing service files and their sidekicks
See also https://github.com/Financial-Times/up-service-files/pull/689
=> Add unique container names for read flow. 

splunk-forwarder.service, varnish@.service, vulcan.service
*Mental note*: This will cause outage, so deploy it per datacenter!
=> Add unique container names for global units

template/template-sidekick@.service, template/template@.service
An example service file with it's sidekick - with some explanation inside.
I can add more comments, i can remove them, or we can just add a link in the README to the service-file which we consider a "role model" instead of keeping a template up-to-date.
I would like to hear your thoughts about this. :)
=> Service file template

services.yaml
No real changes, only formatting of services.yaml 
(Please run "go run format_services_yaml.go" if you haven't added things in the right place, folks!)
=> go run format_services_yaml.go

alphaville-series-rw-neo4j-blue-sidekick@.service, alphaville-series-rw-neo4j-blue@.service, alphaville-series-rw-neo4j-red-sidekick@.service, alphaville-series-rw-neo4j-red@.service, neo4j-backup.service, neo4j-blue-sidekick@.service, neo4j-blue@.service, neo4j-read-blue-sidekick@.service, neo4j-read-red-sidekick@.service, neo4j-red-sidekick@.service, neo4j-red@.service, template/template-sidekick@.service, template/template@.service
-> Add unique container names for alphaville-series & mongo-backup
-> Fix neo4j unique container name generation (add "startsWith" pattern in filter)
-> Update service file template
Tested in xp.
⚠️ Note: a failover needs to be done, when deploying to prod
=> Add unique container names for leftover services

services.yaml
Pushing changes to Prod relating to https://github.com/Financial-Times/content-rw-neo4j/pull/7
=> Content R/W: Add Lifecycle to content managed relationships. 

memberships-rw-neo4j-blue@.service, memberships-rw-neo4j-red@.service
For debugging a production issue.
To be reverted.
Talk to me or Sarah Wells.
=> Change memberships to batch size 1

memberships-rw-neo4j-blue@.service, memberships-rw-neo4j-red@.service
This reverts commit 70c6545dc4d0bed70049a2bbbda24eff18289860.
=> Revert "Change memberships to batch size 1"

elb-dns-registrator.service, services.yaml, tunnel-registrator.service
Making sure we don't remove records as part of registering elb and tunnel records.
https://github.com/Financial-Times/coco-elb-dns-registrator/pull/5
=> Updated dns registrators. 

services.yaml
Adding lifecycle property to annotations-rw
=> Bumping to v30

services.yaml
See https://github.com/Financial-Times/public-annotations-api/pull/8
=> Add read for AlphavilleSeries annotations.

services.yaml
http://git.svc.ft.com/projects/CP/repos/enriched-content-read-api/pull-requests/20/overview
=> Enriched Content new version

services.yaml
This adds better logging so we can see cache hits and misses.
=> Updated varnish image to version 73.

services.yaml
Upgrade to 0.3.0 which uses new neoutils Connect() API to get neo4j
connections.
=> Upgrade to orgs r/w 0.3.0

mongodb@.service, services.yaml
As per discussion 4G should be reasonable
=> Isolate mongo memory usage

services.yaml
goes together with https://github.com/Financial-Times/pub-service-files/pull/37
=> video-mapper v1.2.9 - HTML escape body.

services.yaml
* genres-rw
* locations-rw
* sections-rw
=> Deploy r/w with new neoUtils

services.yaml
* Use exception mapper to ensure errors are logged. - Keith
* Not everything that has a body is an article. (videos) - Huni
=> content-public-read and content-public-read-preview v50 

services.yaml
https://github.com/Financial-Times/nativerw/pull/15
=> Nativerw error handling improvements

services.yaml
cache refresh, format services names, update alpine
Link to App PR: https://github.com/Financial-Times/aggregate-healthcheck/pull/14
=> aggregate-healthcheck v1.1.5

services.yaml
https://github.com/Financial-Times/coco-kafka-bridge/pull/32
=> Upgraded bridge version to use the ageing client

services.yaml
Bump to version with these changes
http://git.svc.ft.com:8080/projects/CP/repos/methode-list-transformer/pull-requests/41/overview
=> Bumped version of Methode List Transformer

neo4j-red@.service, services.yaml
Updating to 2.3.7 for RED only
Also increasing the memory
=> Upgraded neo4j to 2.3.7 - RED only

services.yaml
=> Handle identifiers public-orgs-api

services.yaml
=> Handle identifiers public-things-api

wordpress-article-transformer@.service
Load test works comfortably at 169 Req/s with no 502s or 504s. 99th pct is 248 ms.
=> Set Xms & Xmx for Wordpress Article Transformer

aggregate-healthcheck-sidekick@.service, binary-ingester-sidekick@.service, binary-writer-sidekick@.service, cms-kafka-bridge-pub-prod-sidekick@.service, cms-notifier-sidekick@.service, content-ingester-sidekick@.service, document-store-api-sidekick@.service, methode-content-importer-sidekick@.service, methode-image-binary-transformer-sidekick@.service, methode-image-model-transformer-sidekick@.service, nativerw-sidekick@.service, publish-availability-monitor-sidekick@.service, synthetic-image-publication-monitor-coco-sidekick@.service, system-healthcheck-sidekick.service, wordpress-image-mapper-sidekick@.service
Will be accessed as `<env>/__health?categories=image-publish`.
Example: https://xp-up.ft.com/__health?categories=image-publish
=> Add hc categories for image-publish flow

aggregate-healthcheck-sidekick@.service, cms-kafka-bridge-pub-prod-sidekick@.service, cms-notifier-sidekick@.service, content-ingester-sidekick@.service, document-store-api-sidekick@.service, methode-article-transformer-sidekick@.service, methode-content-importer-sidekick@.service, methode-image-model-transformer-sidekick@.service, methode-list-transformer-sidekick@.service, nativerw-sidekick@.service, video-mapper-sidekick@.service, wordpress-article-transformer-sidekick@.service, wordpress-image-mapper-sidekick@.service
See [here](https://pre-prod-uk-up.ft.com/__health?categories=content-publish) for an example.
=> Content Publish healthcheck category.

neo4j-hot-backup@.service, neo4j-hot-backup@.timer, services.yaml
https://github.com/Financial-Times/neo4j-hot-backup/pull/1
=> Neo4j hot backup

services.yaml, splunk-forwarder.service
https://github.com/Financial-Times/coco-splunk-http-forwarder/pull/6
=> Splunk forwarder versioned. Workers added.

content-public-read-preview@.service, content-public-read@.service, enriched-content-read-api@.service, neo4j-read-blue-sidekick@.service, neo4j-read-red-sidekick@.service, services.yaml
Bumping elb-dns-registrator to v4.0.1 and tunnel-registrator to v1.0.1 to update DNS TTL values to 30s.
=> Update dns ttls

services.yaml
https://github.com/Financial-Times/public-people-api/pull/10
=> Bumped version to include cypher improvements

services.yaml
See
http://git.svc.ft.com/projects/CP/repos/methode-article-transformer/pull-requests/110/overview
=> New MAT release contains more comprehensive healthchecks.

services.yaml
* trying to reduce load on ETCD
* https://github.com/Financial-Times/vulcan-config-builder/pull/20
* https://github.com/Financial-Times/vulcan-config-builder/pull/21
=> Vcb etcd load improvements

content-ingester-neo4j-blue@.service, content-ingester-neo4j-red@.service, content-ingester@.service, notifications-ingester@.service
Set JAVA_OPTS for all 4 instances of the ingester codebase.
=> Content ingester javaopts

services.yaml
https://github.com/Financial-Times/neo-model-utils-go/pull/14
https://env.com/__public-things-api/things/eb058ee2-24c7-3f2d-b3c7-ca242b212cf5
tested in xp
tested in pre-prod
=> Financial Instruments to Public Things API

neo4j-blue@.service, services.yaml
https://github.com/Financial-Times/ft-neo4j/pull/6
=> Updated Neo Blue to have Graphite integration

neo4j-red@.service, services.yaml
https://github.com/Financial-Times/ft-neo4j/pull/6
=> Updated Neo Red to have Graphite integration

financial-instruments-rw-neo4j-blue@.service, financial-instruments-rw-neo4j-red@.service
tested in xp
tested in pre-prod
=> Memory limit for financial-instruments rw

cms-notifier@.service
=> Set java opts for cms-notifier

services.yaml
Cypher improvements for public organisation api - using size versus count
https://github.com/Financial-Times/public-organisations-api/pull/12
=> Cypher perf improvements public organisations api

public-brands-api@.service, public-concordances-api@.service, public-people-api@.service
=> Set cache to 10 minutes for concordances and brands endpoints.

services.yaml
https://github.com/Financial-Times/public-organisations-api/pull/10
=> Financial instruments to org api

services.yaml, v1-content-annotator-binding-service-blue@.service, v1-content-annotator-binding-service-red@.service, v1-content-annotator-blue@.service, v1-content-annotator-brightcove-blue@.service, v1-content-annotator-brightcove-red@.service, v1-content-annotator-red@.service, v2-content-annotator-blue@.service, v2-content-annotator-red@.service
This value is no longer hard coded in the dockerfile.
=> Set Filter Novelties to true

services.yaml
Optimise cypher queries for relationship transfer
https://github.com/Financial-Times/organisations-rw-neo4j/pull/20
=> Bump org-rw version to v0.4.1

services.yaml
Add major mentions predicate to allow V1 annotations for organisations to start to be written
https://github.com/Financial-Times/annotations-rw-neo4j/pull/15
=> Add major mentions support to annotations rw

api-policy-component@.service
Found performance had dropped so bumping memory.
=> Bumped memory on api-policy-component to 384m

services.yaml
Also has fix for not reusing HTTP connections:
http://git.svc.ft.com/projects/CP/repos/api-policy-component/pull-requests/85/overview
http://git.svc.ft.com/projects/CP/repos/api-policy-component/pull-requests/84/overview
=> Updated api-policy-component with redirect fix

services.yaml
Amending since date error message.
=> Bumping to v54

organisations-rw-neo4j-blue@.service, organisations-rw-neo4j-red@.service, people-rw-neo4j-blue@.service, people-rw-neo4j-red@.service, roles-rw-neo4j-blue@.service, roles-rw-neo4j-red@.service, sections-rw-neo4j-blue@.service, sections-rw-neo4j-red@.service, special-reports-rw-neo4j-blue@.service, special-reports-rw-neo4j-red@.service
reverting https://github.com/Financial-Times/up-service-files/pull/876
=> Revert merge pr876

services.yaml
Updating DNS services to use UPP email for CRs.
=> Updating DNS email

concept-suggestion-api@.service, services.yaml
http://git.svc.ft.com:8080/projects/CP/repos/concept-suggestion-api/pull-requests/12/overview
=> bumped version and added necessary variable values

services.yaml
* dockerfile fix - app with pid 1: [v4](http://git.svc.ft.com/projects/CP/repos/methode-list-mapper/pull-requests/3/overview)
* added uuid field to CmsPubEvent msg: [v5](http://git.svc.ft.com/projects/CP/repos/methode-list-mapper/pull-requests/5/overview)
* hc's panic guide links/descriptions fix: [v6](http://git.svc.ft.com/projects/CP/repos/methode-list-mapper/pull-requests/4/overview)
=> mlm: pid1, hc & json fix

services.yaml
For adding "About" for locations, people, topics and organisations. Also bringing in majorMentions for people
https://github.com/Financial-Times/v1-suggestor/pull/23
https://github.com/Financial-Times/v1-suggestor/pull/22
=> v1-suggestor release

concept-suggestion-api@.service, services.yaml
This pushes metrics to graphite
http://git.svc.ft.com/projects/CP/repos/concept-suggestion-api/pull-requests/16/overview
=> Bumped version concept-suggestion-api to v17

services.yaml, v1-content-annotator-binding-service-blue@.service, v1-content-annotator-binding-service-red@.service, v1-content-annotator-blue@.service, v1-content-annotator-brightcove-blue@.service, v1-content-annotator-brightcove-red@.service, v1-content-annotator-red@.service, v2-content-annotator-blue@.service, v2-content-annotator-red@.service
This adds metrics to graphite.
http://git.svc.ft.com/projects/CP/repos/content-annotator/pull-requests/21/overview
=> Bumping content-annotator to v53

cms-kafka-bridge-pub-pre-prod-uk-sidekick@.service, cms-kafka-bridge-pub-pre-prod-uk@.service, cms-kafka-bridge-pub-pre-prod-us-sidekick@.service, cms-kafka-bridge-pub-pre-prod-us@.service, cms-metadata-kafka-bridge-pub-pre-prod-uk-sidekick@.service, cms-metadata-kafka-bridge-pub-pre-prod-uk@.service, cms-metadata-kafka-bridge-pub-pre-prod-us-sidekick@.service, cms-metadata-kafka-bridge-pub-pre-prod-us@.service, services.yaml
**for preprod only**
still need to do concept suggestions
=> changed the bridges so that they read from both publishing US and UK

services.yaml
Bumped v1-suggestor, annotations-rw and public-annotations api to pull in hasAuthor predicate to our annotations
=> Bring in Has_Author annotation

concepts-kafka-bridge-pub-pre-prod-uk-sidekick@.service, concepts-kafka-bridge-pub-pre-prod-uk@.service, concepts-kafka-bridge-pub-pre-prod-us-sidekick@.service, concepts-kafka-bridge-pub-pre-prod-us@.service, services.yaml
=> Updating bridges so that they read from both pub uk and us

services.yaml
See https://github.com/Financial-Times/public-content-by-concept-api/releases/tag/0.1.0
=> Public-content-by-concept-api additional parameters

splunk-forwarder.service
Fixed orphaned containers for the 2 services that are part of splunk-forwarder
https://github.com/Financial-Times/coco-logfilter/pull/28
https://github.com/Financial-Times/coco-splunk-http-forwarder/pull/9
* Done testing in pre-prod.
=> splunk-forwarder: fixed orphan container

services.yaml
And also added coveralls
https://github.com/Financial-Times/public-brands-api/pull/9
=> Added omit if empty to public-brands-api

services.yaml
Fixed orphaned container problem for all kafka bridges:
https://github.com/Financial-Times/coco-kafka-bridge/pull/35
* Tested in pre-prod.
=> Kafka bridge pid1

concept-suggestion-api-sidekick@.service, services.yaml
Application changes: http://git.svc.ft.com:8080/projects/CP/repos/concept-suggestion-api/commits/a63035700a5cebaab3373cb0364a63f87ba2f1d2
=> Bumped version to include concept offsets and added publicly exposed suggest endpoint

alphaville-series-rw-neo4j-blue@.service, alphaville-series-rw-neo4j-red@.service, brands-rw-neo4j-blue@.service, brands-rw-neo4j-red@.service, financial-instruments-rw-neo4j-blue@.service, financial-instruments-rw-neo4j-red@.service, genres-rw-neo4j-blue@.service, genres-rw-neo4j-red@.service, industry-classifications-rw-neo4j-blue@.service, industry-classifications-rw-neo4j-red@.service, locations-rw-neo4j-blue@.service, locations-rw-neo4j-red@.service, memberships-rw-neo4j-blue@.service, memberships-rw-neo4j-red@.service, organisations-rw-neo4j-blue@.service, organisations-rw-neo4j-red@.service, people-rw-neo4j-blue@.service, people-rw-neo4j-red@.service, roles-rw-neo4j-blue@.service, roles-rw-neo4j-red@.service, sections-rw-neo4j-blue@.service, sections-rw-neo4j-red@.service, special-reports-rw-neo4j-blue@.service, special-reports-rw-neo4j-red@.service, subjects-rw-neo4j-blue@.service, subjects-rw-neo4j-red@.service, topics-rw-neo4j-blue@.service, topics-rw-neo4j-red@.service
So that we can alter the batch size per service. The app defaults to 1024 anyway
=> Changed batch size on Neo4J rw apps to be an etcd config value

services.yaml
The delete used also delete the identifiers if it was only just dumbing the concept down (i.e that there was other relationships that need to survive the delete)
Also added coveralls and implemented some simple cypher improvements
https://github.com/Financial-Times/people-rw-neo4j/pull/29
=> Fixed delete in people rw

notifications-rw@.service, services.yaml
See
http://git.svc.ft.com/projects/CP/repos/notifications-rw/pull-requests/52/overview
=> Delay shutdown of notifications-rw for deferred writes.

services.yaml
See https://github.com/Financial-Times/api-policy-component/pull/2 and https://github.com/Financial-Times/api-policy-component/pull/3.
=> Add support for content placeholder type

list-notifications-ingester-sidekick@.service, list-notifications-ingester@.service, list-notifications-push@.service, list-notifications-rw-sidekick@.service, list-notifications-rw@.service, notifications-ingester-sidekick@.service, notifications-ingester@.service, notifications-push@.service, notifications-rw-sidekick@.service, notifications-rw@.service
Follow up on https://github.com/Financial-Times/up-service-files/pull/942 AND fixes for services which were left out.
Tested in xp
=> Fixing filtering for docker names collision around notifications

services.yaml
See
http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/27/overview
=> Add transformation and properties for placeholders to CPR.

services.yaml
All the bug fixes are detailed here: https://github.com/Financial-Times/brands-rw-neo4j/pull/9
=> Bumped the brands-rw version to include some bug fixes

services.yaml
Affected code changes here:
https://github.com/Financial-Times/organisations-rw-neo4j/pull/21
and here:
https://github.com/Financial-Times/organisations-rw-neo4j/pull/22
=> Fix delete organisation rw

kafka-rest-proxy@.service, services.yaml
This change is needed for making kafka-proxy able to handle image binary messages.
=> Increase kafka proxy message size

services.yaml
Release of https://github.com/Financial-Times/delivery-varnish/pull/4
=> Bumped version of varnish

services.yaml
https://github.com/Financial-Times/genres-rw-neo4j/pull/7
Successfully tested in semantic
=> Fix deletes genres rw

services.yaml
https://github.com/Financial-Times/public-annotations-api/pull/13
=> Public-annotations-api now brings back all brands

services.yaml
See
http://git.svc.ft.com/projects/CP/repos/cms-notifier/pull-requests/18/overview
=> New CMS notifier release to accept full system codes.

services.yaml
https://github.com/Financial-Times/industry-classifications-rw-neo4j/pull/6
=> Added support for identifiers in industry classification rw

services.yaml
http://git.svc.ft.com/projects/CP/repos/concept-suggestion-api/pull-requests/20/overview
=> Bumped concept-suggestion-api to fix NPE

services.yaml
https://github.com/Financial-Times/methode-image-model-mapper/pull/2
=> Add /map and /ingest to methode-image-model-mapper

generic-rw-s3-sidekick@.service, generic-rw-s3@.service, services.yaml
Releasing https://github.com/Financial-Times/generic-rw-s3/releases/tag/0.1.0
=> First release of 'generic-rw-s3'

services.yaml
https://github.com/Financial-Times/notifications-push/pull/37
tested in:
* xp
=> notifications-push lists-notifications-push v3.0.6 - more logging

services.yaml
See this [release](https://github.com/Financial-Times/coco-kafka-bridge/releases/tag/v14.1.0).
=> Removing X-Origin-System-ID logic from bridges.

methode-content-placeholder-mapper-sidekick@.service, services.yaml
https://github.com/Financial-Times/methode-content-placeholder-mapper/pull/5
=> Methode-content-placeholder-mapper with /map endpoint

services.yaml
https://github.com/Financial-Times/notifications-push/commit/1beb2fc9d0b31ef53b73dd2b6ba3ef1ba5dbd8e7
=> Carousel notification push feature

services.yaml
The new version contains an additional collection and a refactored code in order to allow the adding of additional with only small configuration changes (code changes)
http://git.svc.ft.com/projects/CP/repos/document-store-api/pull-requests/65/overview
=> Updated the version for the document store api service

internal-content-preview-api@.service
=> fix icp: fetch the public content model, instead the internal one

load-replicator@.service, services.yaml
https://github.com/Financial-Times/load-replicator/pull/5
=> Parameterised notification since date in load replicator

services.yaml
https://github.com/Financial-Times/load-replicator/pull/5
https://github.com/Financial-Times/load-replicator/pull/6
=> Bumped to version 1.0.2

services.yaml
See [this](https://github.com/Financial-Times/api-policy-component/commit/00d620381be834ac7416cf271ccc114ca7d4e546).
=> API Policy Component Update Notifications Filter

services.yaml
Keep the transaction ID if it's supplied.
https://github.com/Financial-Times/concept-ingester/pull/19
=> Concept ingester - transaction ID passthrough

services.yaml
=> Reverting notifications version

generic-rw-s3@.service, services.yaml, v1-content-annotator-binding-service-blue@.service, v1-content-annotator-binding-service-red@.service, v1-content-annotator-binding-service@.service, v1-content-annotator-blue@.service, v1-content-annotator-red@.service, v1-content-annotator@.service, v1-suggestor@.service
https://github.com/Financial-Times/generic-rw-s3/pull/4
https://github.com/Financial-Times/generic-rw-s3/pull/5
https://github.com/Financial-Times/generic-rw-s3/pull/6
Also changed all v1-content-annotator to read from 'V1ConceptAnnotations' to 'v1-content-annotator'
=> Bumped generic-rw-s3 to v1.3.0

services.yaml
https://github.com/Financial-Times/internal-content-api/pull/7
=> bumped internalcontent and internalcontent-preview

fleet-neo4j-unit-healthcheck@.service
Sets the endpoint to be an etcd value rather than hardcoded.
=> Neo4j unit fix

services.yaml
Relates to PR https://github.com/Financial-Times/content-rw-neo4j/pull/15
=> Brands removal

services.yaml
https://github.com/Financial-Times/public-brands-api/pull/10
https://github.com/Financial-Times/public-concordances-api/pull/11
https://github.com/Financial-Times/public-things-api/pull/4
https://github.com/Financial-Times/public-content-by-concept-api/pull/7
https://github.com/Financial-Times/public-organisations-api/pull/14
https://github.com/Financial-Times/public-people-api/pull/12
https://github.com/Financial-Times/public-six-degrees/pull/4
=> Public APIs - CircleCI updates

diamond.service, services.yaml
App pull request https://github.com/Financial-Times/coco-diamond/pull/1/files
=> Diamond fix memory stats

aggregate-healthcheck-sidekick@.service, api-policy-component-sidekick@.service, content-public-read-sidekick@.service, document-store-api-sidekick@.service, enriched-content-read-api-sidekick@.service, internal-content-api-sidekick@.service, public-annotations-api-sidekick@.service, relations-api-sidekick@.service, system-healthcheck-sidekick.service
(a corresponding dashing tile will follow soon)
=> added internalcontent-read category

services.yaml
https://github.com/Financial-Times/internal-content-api/pull/11
=> bumped ICAPI and ICPAPI to version with field removal bugfix

services.yaml
https://github.com/Financial-Times/v1-suggestor/pull/29
Tested in semantic
=> V1 suggestor topics locations as major mentions

services.yaml
This PR relates to a https://github.com/Financial-Times/generic-rw-s3/pull/14
Source code of generic-rw-s3 was updated to support storage of normalised concepts as well as annotations.
=> Concept store support

services.yaml
PR for kafka-bridge gtg endpoint: https://github.com/Financial-Times/coco-kafka-bridge/pull/39
=> Added gtg endpoints for kafka-bridges

services.yaml, system-healthcheck.service
Added gtg endpoints for:
- system-healthcheck https://github.com/Financial-Times/coco-system-healthcheck/pull/41
- methode-article-mapper https://github.com/Financial-Times/methode-article-mapper/pull/21
- api-policy-component https://github.com/Financial-Times/api-policy-component/pull/9
- notifications-rw http://git.svc.ft.com/projects/CP/repos/notifications-rw/pull-requests/65/overview
=> Added gtg endpoints for system-healthcheck, notifications-rw, mam, and apc

services.yaml
Deployment of kafka-bridges that supports native hash
=> kafka-bridge that supports native hash

services.yaml
Reverts Financial-Times/up-service-files#1096
=> Revert "internalcontent-preview"

services.yaml
This reverts commit 2f70add6707cf31f49405e95b9372986d308e3fb.
=> Revert "Revert "internalcontent-preview""

services.yaml
=> Fix conflicts

services.yaml
PR for ntp check fix: https://github.com/Financial-Times/coco-system-healthcheck/pull/42
=> Fixed ntp-check for system-healthcheck

services.yaml
https://github.com/Financial-Times/content-collection-rw-neo4j/pull/5
=> Fix cc-rw-neo4j wrong tech summary in healthcheck

next-video-mapper-sidekick@.service, next-video-mapper@.service, services.yaml
- New service to support videos published in Next Video Editor
- Documentation can be seen here:
https://docs.google.com/a/ft.com/document/d/1ioJCmasEN2unBFnr1QcGj6Cf-QE0NKtgE2YVNYL3lVM/edit?usp=sharing
- App PR (approved & merged): https://github.com/Financial-Times/upp-next-video-mapper/pull/1
=> Next Video Mapper: integrate the new platform

services.yaml
Related PR
https://github.com/Financial-Times/public-annotations-api/pull/17
=> Suppresses annotations of lesser importance for the same concept.

services.yaml
See http://git.svc.ft.com/projects/CP/repos/methode-list-mapper/pull-requests/15/overview &&
http://git.svc.ft.com/projects/CP/repos/methode-list-mapper/pull-requests/16/overview
See also https://sites.google.com/a/ft.com/universal-publishing/documentation/story-specs/3-mar-2017-next-video-platform-work for architecture diagram and other useful information
=> Supporting next-video link files as list items 

services.yaml
Details on notifications-push changes: https://github.com/Financial-Times/notifications-push/pull/43
=> Carousel tid notifications push bugfix

services.yaml
https://github.com/Financial-Times/public-annotations-api/pull/18
https://github.com/Financial-Times/public-things-api/pull/5
https://github.com/Financial-Times/public-content-by-concept-api/pull/8
=> Switch tests to use concepts-rw-neo4j

concepts-rw-neo4j-sidekick@.service, concepts-rw-neo4j@.service, services.yaml
Code: https://github.com/Financial-Times/concepts-rw-neo4j/pull/1, https://github.com/Financial-Times/concepts-rw-neo4j/pull/2, https://github.com/Financial-Times/concepts-rw-neo4j/pull/3
Tested in Semantic
=> Initial relase concepts rw neo4j

services.yaml
https://github.com/Financial-Times/organisations-rw-neo4j/pull/28
Fixed so now can concord an org that is a Thing with an Organisation
=> Fix concordance within Org-Rw-Neo4j

image-resolver-sidekick@.service, image-resolver@.service, services.yaml
Add a new service image-resolver: https://github.com/Financial-Times/image-resolver
=> Image resolver service

services.yaml
Fix to support story package deletion for videos
See https://github.com/Financial-Times/content-collection-rw-neo4j/releases/tag/1.1.0
=> Content-Collection-RW supporting DELETEs of story packages for next-video

services.yaml
Generate a story package UUID when videos with related content are published.
App PR: https://github.com/Financial-Times/upp-next-video-mapper/pull/3
Tested in `video` cluster
=> Handle story package for video content (next video mapper)

services.yaml
https://github.com/Financial-Times/aggregate-concept-transformer/pull/3
https://github.com/Financial-Times/concepts-rw-neo4j/pull/4
=> Bump aggregate-concept-transformer and concepts-rw-neo4j to new versions which can handle people data

services.yaml
https://github.com/Financial-Times/coco-fleet-unit-healthcheck/pull/17
=> Fleet Unit Healthcheck - Update links and summaries.

services.yaml
[PR](https://github.com/Financial-Times/public-organisations-api/pull/16)
Tested in XP
=> Improve public-organisation-api perf by removing memberships

services.yaml
[PR](https://github.com/Financial-Times/post-publication-combiner/pull/4)
Tested in XP.
=> Remove content type from force endpoint

content-ingester@.service, methode-article-image-set-mapper-sidekick@.service, methode-article-image-set-mapper@.service, services.yaml
https://github.com/Financial-Times/methode-article-mapper/pull/28
https://github.com/Financial-Times/methode-article-image-set-mapper/pull/1
http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/41/overview
=> inline image-sets

zookeeper.service
- logging config based on zk sources:
https://github.com/apache/zookeeper/blob/ec20c5434cc8a334b3fd25e27d26dccf4793c8f3/bin/zkEnv.sh#L73
- more on `UPP2-186`
- tried in XP
=> Fix zk persistence config and reconfigure logging to avoid spam

services.yaml
https://github.com/Financial-Times/methode-image-model-mapper/pull/10
=> PNG graphics and a new type.

services.yaml
http://git.svc.ft.com/projects/CP/repos/notifications-rw/pull-requests/74/overview
=> bumped notifications-rw to version with new content type support

services.yaml
- https://github.com/Financial-Times/burrow/pull/2
=> Upgrade burrow to fix exit code

splunk-forwarder.service
See https://github.com/Financial-Times/coco-logfilter/releases/tag/1.1.3
Tested in `video` cluster, see extracted fields from Splunk (e.g. `event` or `queue_topic`):
```
{    [-]    
HOSTNAME:     ip-172-24-85-207.eu-west-1.compute.internal    
MACHINE_ID:     d4480bd226404f6c9f5cb5117bd3825a    
MESSAGE:     {"event":"consume_queue","level":"info","msg":"Ignoring message with different Origin-System-Id: http://cmdb.ft.com/systems/wordpress","queue_topic":"NativeCmsPublicationEvents","service_name":"next-video-annotations-mapper","time":"2017-06-13T15:35:53Z"}    
SYSTEMD_UNIT:     next-video-annotations-mapper@2.service       
environment:     video    
event:     consume_queue    
level:     info    
msg:     Ignoring message with different Origin-System-Id: …
```
=> A step to support structured logging

services.yaml
Enabling sequential deployment for all the annotations related services, as part of the platinum-ise annotations work.
=> Add sequential deployment for annotations related services.

services.yaml
https://github.com/Financial-Times/methode-article-image-set-mapper/pull/3
=> Methode-article-image-set-mapper timeformat fix

aggregate-healthcheck-sidekick@.service, next-video-annotations-mapper-sidekick@.service, next-video-annotations-rw-neo4j-sidekick@.service, next-video-content-annotator-sidekick@.service, public-annotations-api-sidekick@.service, system-healthcheck-sidekick.service, v1-annotations-rw-neo4j-sidekick@.service, v1-content-annotator-binding-service-sidekick@.service, v1-content-annotator-sidekick@.service, v1-suggestor-sidekick@.service
- create `annotations-read` category 
- create `annotations-publish` category
- update `read` category with `public-annotations` service
=> Create annotations-read and annotations-publish categories.

services.yaml
https://github.com/Financial-Times/methode-image-model-mapper/pull/12
=> Graphics based on methode metadata

services.yaml
See https://github.com/Financial-Times/concept-search-api/pull/32
=> Concept search API search all types for mentions and about

mongo-backup@.timer
Changing backup start time from 11:00 to 01:00.
=> Change MongoDB backup time

services.yaml
Enriched Content API: [PR](http://git.svc.ft.com/projects/CP/repos/enriched-content-read-api/pull-requests/32/overview)
Tested in XP
=> Include annotations in read KPIs

services.yaml
http://git.svc.ft.com/projects/CP/repos/enriched-content-read-api/pull-requests/33/overview
=> Use new resilient client which does not log successful requests

services.yaml
And upgraded circle ci 2
https://github.com/Financial-Times/people-rw-neo4j/pull/36
=> Incorporated the version of people-rw-neo4j with the transid handling

services.yaml
https://github.com/Financial-Times/coco-kafka-bridge/pull/41
=> Update kafka briges

services.yaml
Kafka topic checks removed from kafka bridges.
https://github.com/Financial-Times/coco-kafka-bridge/pull/41
=> Remove kafka bridges topic check

services.yaml
It doesn't currently support Basic TME Concepts
=> Rolling back Concept RW ES

list-notifications-push@.service, notifications-push@.service
Testing in pre-prod:
https://github.com/Financial-Times/notifications-push/pull/44
=> Testing topic healthcheck

list-notifications-push@.service, notifications-push@.service
This reverts commit ae8ceaf775170d684cb32e776d82d861a4a0b536.
=> Revert "Testing topic healthcheck"

coreos-version-checker.service, services.yaml
PR for code base: https://github.com/Financial-Times/coreos-version-checker/pull/4
=> Added fix for cve severities

services.yaml
Reverts Financial-Times/up-service-files#1283
=> Revert "Release version for in-article layout component."

services.yaml
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/18
=> Fix inline links

services.yaml
improved logging +400 error request
=> Concept rw es proper error logging

services.yaml
See here for more details:
https://www.varnish-cache.org/lists/pipermail/varnish-announce/2017-August/000722.html
=> Varnish security vulnerability

services.yaml
https://github.com/Financial-Times/public-organisations-api/pull/17
https://github.com/Financial-Times/public-people-api/pull/13
=> Added Direct Type to public-people-api and public-organisations-api's

services.yaml
https://github.com/Financial-Times/public-annotations-api/pull/22
Tested in semantic
=> Deploy released version

services.yaml
https://github.com/Financial-Times/methode-article-mapper/pull/34
=> methode-article-mapper to strip recommended tags

services.yaml
https://github.com/Financial-Times/api-policy-component/pull/24
Tested recommended tags appearance/non-appearance in rj's endpoints and database collections.
More to test in pre-prod.
=> api-policy-component:64.4.2-rj-norecommended-rc1 no recommended

services.yaml
See https://github.com/Financial-Times/notifications-push/pull/49
=> New-notifications-push to wrap scoop field within standout field in response

services.yaml
Please see https://github.com/Financial-Times/public-annotations-api/pull/23
=> Exposed FIGI code in annotations

services.yaml
Please see https://github.com/Financial-Times/api-policy-component/pull/27
=> Restrict access to non-syndicatable content for B2B

services.yaml
https://github.com/Financial-Times/public-people-api/pull/15
=> Updated dockerfile for the public-people-api as it wasn't using govendor

services.yaml
https://github.com/Financial-Times/roles-rw-neo4j/pull/10
=> Update roles rw v0.1.7

services.yaml
Made it use vendoring.
https://github.com/Financial-Times/public-organisations-api/pull/20
Tested in semantic
=> Public Organisations API - Updated Dockerfile

services.yaml
https://github.com/Financial-Times/public-things-api/pull/9
New fields and relationships
=> Bumped the version to bring in the changes to Public Things API

services.yaml
https://github.com/Financial-Times/methode-article-mapper/pull/38
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/23
https://github.com/Financial-Times/internal-content-api/pull/22
=> Webapp fields

services.yaml
Please see https://github.com/Financial-Times/delivery-varnish/pull/17
=> Restrict current notifications-push access via Fastly

services.yaml
https://github.com/Financial-Times/concepts-rw-neo4j/pull/11
=> Concepts-rw to have the extra relationship and fields for section migration

aggregate-concept-transformer@.service, services.yaml
https://github.com/Financial-Times/aggregate-concept-transformer/pull/7
=> Bump version of aggy, added new variables

services.yaml
https://github.com/Financial-Times/content-model/pull/10
https://github.com/Financial-Times/methode-article-mapper/pull/37
=> Added withContributorPayment value to canBeSyndicated field

services.yaml
=> Match thing not content

binary-writer@.service, services.yaml
https://github.com/Financial-Times/binary-writer/pull/1
https://github.com/Financial-Times/binary-writer/pull/2
=> Fix binary writer

services.yaml
https://github.com/Financial-Times/memberships-rw-neo4j/pull/12
https://github.com/Financial-Times/memberships-rw-neo4j/pull/11
=> Added helm integration and sirupsen changes to membership rw neo4j

services.yaml
https://github.com/Financial-Times/wordpress-article-mapper/pull/10
=> Wam helm integration

services.yaml
https://github.com/Financial-Times/relations-api/pull/3
=> Helmify relations-api

services.yaml
https://github.com/Financial-Times/industry-classifications-rw-neo4j/pull/13
- tested in XP
=> industry-classifications-rw helm integration 

services.yaml
https://github.com/Financial-Times/roles-rw-neo4j/pull/11
=> Includes sirupsen fix and membershiprole fix in roles-rw

enriched-content-read-api@.service, services.yaml
https://github.com/Financial-Times/enriched-content-read-api/pull/1
=> Enriched content api helm

services.yaml
- https://github.com/Financial-Times/concept-ingester/pull/21
- tested in XP
=> Concept ingester dual stack

services.yaml
https://github.com/Financial-Times/aggregate-concept-transformer/pull/14
=> Build from released version

services.yaml
Simple App PR with a small fix: https://github.com/Financial-Times/relations-api/pull/5
=> Rolling out helm 2.6.0 fixes

README.md, template/template@.service, template/template@.service-private
...to remove references to up-registry.
=> Updating template

services.yaml
- only helm changes - https://github.com/Financial-Times/burrow/pull/3
- https://github.com/Financial-Times/burrow/compare/1.0.2...2.1.0
=> Bring burrow in sync with k8s

services.yaml
- no code changes, only helm integration Financial-Times/coco-system-healthcheck#44
- https://github.com/Financial-Times/coco-system-healthcheck/compare/1.0.7...1.0.8
=> Update sys-hc to latest version with helm integration

services.yaml
- no code changes - https://github.com/Financial-Times/methode-article-image-set-mapper/pull/6
- https://github.com/Financial-Times/methode-article-image-set-mapper/compare/1.2.0...1.4.0
=> Update maism to latest version with helm integration

services.yaml
- helm integration only - no code changes https://github.com/Financial-Times/methode-image-binary-mapper/pull/4
- source the version correctly in the dockerfile https://github.com/Financial-Times/methode-image-binary-mapper/pull/5
- https://github.com/Financial-Times/methode-image-binary-mapper/compare/v1.0.2...1.0.4
=> update mibm to latest version with helm integration

services.yaml
- helm integration only, no code changes: https://github.com/Financial-Times/methode-image-set-mapper/pull/8
- https://github.com/Financial-Times/methode-image-set-mapper/pull/9
- https://github.com/Financial-Times/methode-image-set-mapper/compare/9.1.1...9.1.3
=> Update mism to latest version with helm integration

services.yaml
See:
* https://github.com/Financial-Times/content-rw-neo4j/pull/27
* https://github.com/Financial-Times/base-ft-rw-app-go/pull/25
=> Content-rw-neo4j with OpenAPI endpoint

services.yaml
https://github.com/Financial-Times/public-concordances-api/pull/20
=> Public Concordances API - show UPP identifiers

methode-article-mapper@.service, services.yaml
* tested in k8s-delivery-upp-eu
* tested in rj-up
* https://trello.com/c/8Xpx3AZa/18-methode-article-mapper
* https://github.com/Financial-Times/methode-article-mapper/pull/15
* `methode-article-mapper:1.6.0-k8s-dualstack-rc1`
* https://github.com/Financial-Times/methode-article-mapper/tree/1.6.0-k8s-dualstack-rc1
=> Helm, Dual stack, methode-article-mapper

services.yaml
- helm integration only https://github.com/Financial-Times/image-resolver/pull/6/files
- https://github.com/Financial-Times/image-resolver/compare/2.0.1...2.0.2
=> Update image-resolver to include helm integration

services.yaml
- helm integration, no other changes https://github.com/Financial-Times/content-collection-unfolder/pull/9
- https://github.com/Financial-Times/content-collection-unfolder/compare/1.1.0...1.2.0
=> Helm integration

services.yaml
- only helm integration and helm config fixes, no code changes
- https://github.com/Financial-Times/public-content-by-concept-api/pull/11
- https://github.com/Financial-Times/public-content-by-concept-api/pull/12
- https://github.com/Financial-Times/public-content-by-concept-api/compare/1.2.0...1.3.1
=> Update concordances and content by concept APIs

services.yaml
- helm integration only, no code changes https://github.com/Financial-Times/organisations-rw-neo4j/pull/31
- https://github.com/Financial-Times/organisations-rw-neo4j/compare/0.5.8...0.5.9
=> update orgs rw to latest version with helm integration

services.yaml
- only helm integration, no code changes: https://github.com/Financial-Times/people-rw-neo4j/pull/38
- https://github.com/Financial-Times/people-rw-neo4j/compare/0.2.1...2.0.0
=> Update people-rw to latest version with helm integration

services.yaml
- helm config changes only https://github.com/Financial-Times/concept-suggestion-api/pull/3
- https://github.com/Financial-Times/concept-suggestion-api/compare/1.46.0...1.47.0
=> Get CSAPI in sync with K8S

services.yaml
- only helm integration https://github.com/Financial-Times/list-notifications-rw/pull/23
- https://github.com/Financial-Times/list-notifications-rw/compare/0.1.5...0.1.6
=> Update list notifications rw to latest version with helm integration

services.yaml
- helm integration only, no code changes: 
- https://github.com/Financial-Times/post-publication-combiner/pull/7
- https://github.com/Financial-Times/post-publication-combiner/pull/
- https://github.com/Financial-Times/post-publication-combiner/compare/1.1.1...1.2.0
=> Update ppc to latest version with helm integration

services.yaml
See: https://github.com/Financial-Times/public-annotations-api/pull/33
=> Public annotations API infers implicitlyClassifiedBy on read

services.yaml
- https://github.com/Financial-Times/methode-image-model-mapper/pull/14
=> miim latest version with correct version sourcing in the Dockerfile

services.yaml
Changes since `0.0.5`
- 0.0.6: https://github.com/Financial-Times/financial-instruments-rw-neo4j/pull/4
- 0.0.7: https://github.com/Financial-Times/financial-instruments-rw-neo4j/pull/6
- 0.0.9: https://github.com/Financial-Times/financial-instruments-rw-neo4j/pull/7
=> Update to FI rw to latest version

services.yaml
https://github.com/Financial-Times/concept-search-index-mapping/pull/11
=> Fix to smartlogic elasticsearch alias filter

services.yaml
- helm integration, Dockefile, circle config changes: https://github.com/Financial-Times/content-collection-rw-neo4j/pull/7
=> Helm integration + small changes

services.yaml
* Fix for journald logging - https://github.com/Financial-Times/content-public-read/tree/1.1.1
* Map to URLs for Graphic type - https://github.com/Financial-Times/content-public-read/tree/1.1.2
=> Ops cop changes for CPR/CPR-preview 

methode-article-internal-components-mapper@.service, methode-content-collection-mapper@.service, methode-content-placeholder-mapper@.service, methode-list-mapper@.service, services.yaml
Ingesters, doc-store, reader apps remain.
=> Reverting only mappers that replace placeholder uuids. 

services.yaml
- vendoring, circle CI update, Helm integration
- https://github.com/Financial-Times/public-six-degrees/pull/5
- https://github.com/Financial-Times/public-six-degrees/pull/6
=> Update 6 degrees api to latest version with helm integration

services.yaml
https://github.com/Financial-Times/api-policy-component/releases/tag/65.1.0
=> Ops - Coalesce stack traces into single log events for APC

services.yaml
See this PR for details: https://github.com/Financial-Times/pac-annotations-mapper/pull/7
=> Adding monitor logging to PAC annotation mapper

services.yaml
https://github.com/Financial-Times/coco-kafka-bridge/pull/45
=> Added error message in log & k8s configs

services.yaml
=> Increased service count for CPR

methode-article-internal-components-mapper@.service, methode-content-collection-mapper@.service, methode-content-placeholder-mapper@.service, methode-list-mapper@.service, services.yaml
* https://github.com/Financial-Times/methode-content-placeholder-mapper/pull/17 1.0.2
promotionalImage is an object with id field.
* https://github.com/Financial-Times/enriched-content-read-api/pull/5 1.2.1
expanding images on complementary parts
* https://github.com/Financial-Times/image-resolver/pull/7 
expanding promotionalImages with id 2.1.0
=> Content placeholders for Wordpress - run 2

content-exporter-sidekick@.service, content-exporter@.service, content-rw-s3-sidekick@.service, content-rw-s3@.service, services.yaml
Two new services added as part of Daily Exports story: content-exporter and content-rw-s3
https://github.com/Financial-Times/content-rw-s3/pull/1
https://github.com/Financial-Times/content-exporter/pull/1
=> Content export

services.yaml
* https://github.com/Financial-Times/methode-content-placeholder-mapper/pull/19
* https://github.com/Financial-Times/methode-content-collection-mapper/pull/8
=> adding one healthcheck entry in two applications

services.yaml
Removed brands and content rw from services list.
https://github.com/Financial-Times/concept-ingester/pull/22
=> Synced k8s settings with prod

services.yaml
- https://github.com/Financial-Times/document-store-api/pull/9
- https://github.com/Financial-Times/list-notifications-rw/pull/24
- https://github.com/Financial-Times/notifications-rw/pull/6
=> Update some apps - helm changes only

services.yaml
- helm changes only, no code changes
- https://github.com/Financial-Times/concept-search-index-mapping/pull/13
- https://github.com/Financial-Times/concept-search-index-mapping/compare/0.0.10...0.0.11
=> Update concept-search-reindexer to latest version with helm integration

services.yaml
https://github.com/Financial-Times/coco-kafka-bridge/pull/46
=> Releasing to preprod:

services.yaml
https://github.com/Financial-Times/people-rw-neo4j/pull/39
=> People rw imageurl

methode-article-internal-components-mapper@.service, methode-article-mapper@.service, services.yaml
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/28
https://github.com/Financial-Times/methode-article-mapper/pull/40
=> API Host can now be configured using an environment variable

services.yaml
Please see https://github.com/Financial-Times/content-exporter/releases/tag/1.2.0 (PR https://github.com/Financial-Times/content-exporter/pull/11)
=> Content-exporter: healtcheck improvements + helm config

services.yaml
- New stable version containing helm improvements: healthcheck, pod affinity, memory limits.
https://github.com/Financial-Times/annotations-mapper/pull/6
=> Annotations mapper fix helm

services.yaml
Financial-Times/cms-notifier#8
=> Log when cms notifier is unhealthy

services.yaml
Please see https://github.com/Financial-Times/annotations-rw-neo4j/releases/tag/2.2.0
=> Annotations-rw-neo4j & suggestions-rw-neo4j: healtcheck improvements + helm config

services.yaml
* https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/29
=> design.layout and design.theme mapping of content packages

services.yaml
https://github.com/Financial-Times/internal-content-api/pull/23
=> Update internal content apis to latest version, helm changes only

services.yaml
Codebase PR: https://github.com/Financial-Times/coreos-version-checker/pull/7
=> Cvss parsing fixed

services.yaml
Financial-Times/coco-system-healthcheck#45
=> Edit Updated system healthcheck helm integration 

services.yaml
Added affinity to the helm configuration.
Improved memory configuration.
Added healthcheck timeout.
https://github.com/Financial-Times/concepts-rw-neo4j/pull/21
=> Helm improvements

services.yaml
App PR: https://github.com/Financial-Times/concept-search-api/pull/45
=> Concept Search API - helm improvements

services.yaml
https://github.com/Financial-Times/kafka-lagcheck/pull/7
=> Upgrade kafka-lagcheck to latest stable

services.yaml
App PR: https://github.com/Financial-Times/concept-rw-elasticsearch/pull/36
=> Concept rw elastic helm improvements

services.yaml
https://github.com/Financial-Times/binary-writer/pull/6
- tested in XP, works
=> Improved healthcheck + helm config

services.yaml
PR: https://github.com/Financial-Times/pac-annotations-mapper/pull/8
=> K8s parity/pac ann mapper

services.yaml
https://github.com/Financial-Times/content-preview/pull/26
=> Improved healthcheck & helm config

services.yaml
See https://github.com/Financial-Times/content-rw-neo4j/pull/28 (tag https://github.com/Financial-Times/content-rw-neo4j/releases/tag/2.1.0)
=> Content-rw-neo4j: Improved healthcheck + helm config

services.yaml
[PR](https://github.com/Financial-Times/public-concordances-api/pull/21)
=> Update public-concordances-api - HELM resiliency

services.yaml
Codebase PR: https://github.com/Financial-Times/internal-content-api/pull/24
=> K8s hc & helm

services.yaml
https://github.com/Financial-Times/coco-system-healthcheck/pull/46
=> Helm changes only to system-hc

services.yaml
[Application code PR](https://github.com/Financial-Times/public-annotations-api/pull/36)
NOTE: Needs to be updated with the final version.
=> Public Annotations Api - helm changes for service resiliency.

services.yaml
See https://github.com/Financial-Times/content-collection-rw-neo4j/pull/8 (tag: https://github.com/Financial-Times/content-collection-rw-neo4j/releases/tag/1.3.0)
=> Content-collection-rw-neo4j: Improved healthcheck + helm config

services.yaml
App PR: https://github.com/Financial-Times/post-publication-combiner/pull/10
=> Post publication combiner k8s

services.yaml
- k8s improvements: healthcheck timeout, pod affinity, memory
=> Kafka bridges helm improvements

services.yaml
Codebase PR: https://github.com/Financial-Times/content-collection-unfolder/pull/12
=> K8s hc & helm improvements

services.yaml
https://github.com/Financial-Times/generic-rw-s3/pull/21
=> K8S healthcheck & helm improvements

services.yaml
Code Change: https://github.com/Financial-Times/upp-next-video-annotations-mapper/pull/9
Tested in semantic cluster and k8s
=> Update app for k8s migration

services.yaml
https://github.com/Financial-Times/concept-ingester/pull/24
=> Deploy version with changed config in helm chart

services.yaml
Please see https://github.com/Financial-Times/upp-next-video-mapper/pull/12 (tag https://github.com/Financial-Times/upp-next-video-mapper/releases/tag/1.6.0)
=> Next-video-mapper: Improved healthcheck + helm config

services.yaml
[PR](https://github.com/Financial-Times/methode-article-image-set-mapper/pull/8)
=> Methode-article-image-set-mapper helm config

services.yaml
Please see https://github.com/Financial-Times/api-policy-component/pull/32
(tag https://github.com/Financial-Times/api-policy-component/releases/tag/66.2.0)
=> api-policy-component: Improved healthcheck + helm config

methode-image-set-mapper@.service, services.yaml
Codebase PR: https://github.com/Financial-Times/methode-image-set-mapper/pull/10
=> K8s hc & helm, test version

services.yaml
https://github.com/Financial-Times/methode-content-collection-mapper/pull/9
=> methode-content-collection-mapper:1.1.2

services.yaml
https://github.com/Financial-Times/public-organisations-api/pull/21
=> Public orgs api k8s helm3 helm with a vengeance

services.yaml
No effective changes for Coco, just making sure the latest versions are deployed
* https://github.com/Financial-Times/concept-exporter/releases/tag/1.2.0
* https://github.com/Financial-Times/content-exporter/releases/tag/1.2.1
* https://github.com/Financial-Times/upp-next-video-annotations-mapper/releases/tag/1.5.0
=> Fixing OOMs in K8s PROD

public-things-api@.service, services.yaml
https://github.com/Financial-Times/public-things-api/pull/11
=> Public things api - k8s migration improvements

services.yaml
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/30  
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/31
=> methode-article-internal-components-mapper affinity

services.yaml
[Codebase PR](https://github.com/Financial-Times/methode-list-mapper/pull/8)
=> methode-list-mapper k8s migration improvements

services.yaml
[Codebase PR](https://github.com/Financial-Times/coco-synthetic-image-publication-monitor/pull/20)
=> coco-synthetic-image-monitor k8s improvements

services.yaml
[Codebase PR](https://github.com/Financial-Times/public-six-degrees/pull/7)
=> Public six degrees k8s migration

services.yaml
Please see https://github.com/Financial-Times/cms-notifier/pull/10 (tag https://github.com/Financial-Times/cms-notifier/releases/tag/1.58.0)
=> Cms-notifier: Improved healthcheck + helm config

services.yaml
[Codebase PR](https://github.com/Financial-Times/public-people-api/pull/17)
=> Public people api - k8s improvements

services.yaml
https://github.com/Financial-Times/notifications-push/pull/56
=> Notifications push helm improvements

services.yaml
https://github.com/Financial-Times/burrow/pull/5
tested in xp, pre-prod
=> burrow memory, affinity

services.yaml
Send an update notification instead of a delete notification when an article is removed from the collection.
https://github.com/Financial-Times/content-collection-unfolder/pull/13
=> Replace delete notifications with update notifications

services.yaml
Adjusted bridges for k8s staging env.
Release link: https://github.com/Financial-Times/coco-kafka-bridge/releases/tag/15.1.1
PR: https://github.com/Financial-Times/coco-kafka-bridge/pull/49
=> Releasing bridges 15.1.1 to prod

services.yaml
https://github.com/Financial-Times/notifications-push/pull/57
=> Improved Notifications push subscriber logging

cms-kafka-bridge-k8s-pub-prod-eu-sidekick@.service, cms-kafka-bridge-k8s-pub-prod-eu@.service, cms-kafka-bridge-k8s-pub-prod-us-sidekick@.service, cms-kafka-bridge-k8s-pub-prod-us@.service, cms-metadata-kafka-bridge-k8s-pub-prod-eu-sidekick@.service, cms-metadata-kafka-bridge-k8s-pub-prod-eu@.service, cms-metadata-kafka-bridge-k8s-pub-prod-us-sidekick@.service, cms-metadata-kafka-bridge-k8s-pub-prod-us@.service
This needs a proper eyeball review since testing it in a lower env will distort the bridge functionality as it has a consumer ID.
I left the concept bridge as it points to the vanity and therefore should continue to work in most situations.
=> Bridges for Coco delivery for message on K8s Publishing cluster.

services.yaml
- App PR: https://github.com/Financial-Times/upp-next-video-content-collection-mapper/pull/7
=> Fixing logs timestamp for video-content-collection-mapper
