Financial-Times/up-service-files

service-files/aggregate-healthcheck-sidekick@.service

Will route all requests going through the ELB to aggregate-healthcheck by default. Overriding the Host header will allow you to get to anything else though.

Expose aggregate-healthcheck to ELB

---

service-files/annotations-api-sidekick@.service
service-files/api-policy-component-sidekick@.service
service-files/binary-ingester-sidekick@.service
service-files/binary-writer-sidekick@.service
service-files/cms-notifier-sidekick@.service
service-files/content-by-concept-api-sidekick@.service
service-files/content-writer-sesame-sidekick@.service
service-files/document-store-api-sidekick@.service
service-files/enriched-content-read-api-sidekick@.service
service-files/fastftxf-sidekick@.service
service-files/ingester-content-sidekick@.service
service-files/ingester-semantic-sidekick@.service
service-files/methode-article-transformer-sidekick@.service
service-files/methode-content-importer-sidekick@.service
service-files/methode-image-binary-transformer-sidekick@.service
service-files/methode-image-model-transformer-sidekick@.service
service-files/nativerw-sidekick@.service
service-files/organisation-read-api-sidekick@.service
service-files/people-read-api-sidekick@.service
service-files/semantic-reader-sidekick@.service
service-files/wp-notifier-sidekick@.service
service-files/wp-transformer-sidekick@.service

remove reference to elb host almost everywhere. (all services except aggregating health check, which may or may not need more thought)

remove to ELB host name in health routing

---

service-files/aggregate-healthcheck-sidekick@.service
service-files/annotations-api-sidekick@.service
service-files/api-policy-component-sidekick@.service
service-files/binary-ingester-sidekick@.service
service-files/binary-writer-sidekick@.service
service-files/content-by-concept-api-sidekick@.service
service-files/content-writer-sesame-sidekick@.service
service-files/document-store-api-sidekick@.service
service-files/enriched-content-read-api-sidekick@.service
service-files/fastftxf-sidekick@.service
service-files/graphdb-master-sidekick@.service
service-files/graphdb-worker-sidekick@.service
service-files/ingester-content-sidekick@.service
service-files/ingester-semantic-sidekick@.service
service-files/kafka-sidekick.service
service-files/methode-article-transformer-sidekick@.service
service-files/methode-content-importer-sidekick@.service
service-files/methode-image-binary-transformer-sidekick@.service
service-files/methode-image-model-transformer-sidekick@.service
service-files/mongodb-sidekick@.service
service-files/nativerw-sidekick@.service
service-files/organisation-read-api-sidekick@.service
service-files/people-read-api-sidekick@.service
service-files/semantic-reader-sidekick@.service
service-files/splunk-sidekick.service
service-files/synthetic-image-publication-monitor-sidekick@.service
service-files/varnish-sidekick@.service
service-files/wp-notifier-sidekick@.service
service-files/wp-transformer-sidekick@.service
service-files/zookeeper-sidekick.service

This fixes the bug where once main service is stopped and sidekicks stop
along with it, once main service it restarted, sidekick remains dead.
ReloadPropagatedFrom ensures that the reload of the main service is
propogated to the sidekick

Sidekicks to ReloadPropagatedFrom main services

---

service-files/splunk-forwarder.service

This doesn't work being in up-registry and registry itself uses the same
image. Reason its angelx and not coco, is that there is currently an
issue with dockerhub that is preventing us from deleting the coco
automated build. And the build won't work. So temp work around, putting
it on my account

Externalise splunk forwarder images to dockerhub

---

service-files/fleet-unit-healthcheck-sidekick.service

This also fixes the problem when fleet-unit-hc moves to other machine, and agg-hc continues to look for fleet-unit-hc on the old machine as well.

Removed host name from fleet-unit-hc routing rule

---

services-pre-prod.yaml

This uses a new dwbase in dockerhub which has no ft deps in it. Also, we
use official alpine openjdk8.

Upgrade to a version that is based on new dwbase (pre-prod)

---

service-files/mongo-backup.service
service-files/mongo-backup.timer
services.yaml

* same service, timer and definition as on the `pre-prod` branch.
* I left the schedule the same as in `pre-prod` so we're here to see it happen. AFAIK we will only run this for a few days anyway. 
* added necessary data in `etcd` in prod as well

Adding mongo-backup service, timer and service definition

---

services.yaml

Leaving the unit file in, in case we want to use it for anything in the
future

Unschedule skydns, currently not used by anything

---

restorage-mongo-sidekick@.service
restorage-mongo@.service
services.yaml

This adds an instance of up-restorage to production, configured to point at mongodb.  Among other things, this gives a nice way to stream individual collections of data out of mongodb via curl, which can then (for example) be piped into other clusters, or into other restorage backends (e.g, elasticsearch)
Note that this app is single instance and not explicitly monitored etc at the moment as it's currently more of an operational tool than anything else.

added restorage instance running on mongo

---

splunk-forwarder.service

As it currently stands stdout is logged to a json file in
`/var/lib/docker/containers` and can consume all FS space. Logs are
already going into journald by virtue of process being wrapped in
`systemd` these however are managed and will not consume ALL space.

Explicitly turn off docker logging for filter and http-forwarder

---

mongo-backup.service

* read the bucket, data dir, and s3 domain from the service file instead of etcd
* the data dir and s3 domain are the same in all environments, so no reason to have them in etcd
* to simplify the configuration, we can keep all backups in the same bucket, as the backup file names are suffixed with the environment
* otherwise, to automate things, we would either have to dynamically build the bucket name in the provisioner
* we currently have 1 bucket for pre-prod, 1 bucket for prod, and 2 prod envs
* the other option is to manually add the values after the provisioner is done, which is not desirable

Standardizing mongo backup config

---

notifications-ingester@.service

All ingester deployments use the coco/ingester Docker image, with
configuration provided in the service file.

Copy fixes from dynpub branch.

---

tunnel-registrator.service

Konstructor will append a record to the node if one already exists. What
we want is to guarantee replacement. This will make the service fail if
we were unable to delete AND create an entry, making the operation
atomic

Make sure we delete the node before creating a record

---

document-store-api-sidekick@.service

The redirect is set at "public-services" level for doc-store-api. Tested in XP.

Add middleware to redirect content to content-read endpoint.

---

services.yaml

contains timestamp fixes, reverting non-ft source content publish check, etc.

bump pam version

---

services.yaml

Deploy version of SIPM that runs the application process as PID 1 in
attempt to fix the issue with orphaned containers

Deploy sipm with PID 1 fix

---

document-store-api-sidekick@.service
elb-dns-registrator.service
services.yaml
varnish-sidekick@.service

* Using new version of elb-dns-registrator to support multiple domain creation - $ENV-up (current) and $ENV-up-read (for read endpoints)
Additional changes from pre-prod:
* Fixing varnish's Host regex
* Versions of doc store api and api policy component. Rename opening to openingXML and apply INCLUDE_RICH_CONTENT policy to openingXML
* Bump PAM version. Skip checking live content from notifications endpoint
* Deploy version of SIPM that runs the application process as PID 1 in
attempt to fix the issue with orphaned containers

Register read dns

---

services.yaml
v1-suggestor-sidekick@.service
v1-suggestor@.service

V1 suggestor is working in XP 
- it's getting the messages from the kafka queue
- generating concept suggestions
- putting concept suggestions on the right queue
- these concept suggestions are ignored by the v2-annotator because of the origin

Add v1 suggestor

---

api-policy-component-sidekick@.service
document-store-api-sidekick@.service

This is part of the effort to create a read endpoint healthcheck which
would monitor availability of at least one service being available

Implement short heartbeats for read services

---

services.yaml

* disables logging to file for these apps, leaving only logging to console - this should help with disk space
* most apps also contain the "make Java PID 1" change which should prevent the leftover container syndrome
* tried in XP, all green, will also check logs to make sure console logging still works

Updating Java app versions - disables logging to file

---

services.yaml

* http://git.svc.ft.com/projects/CP/repos/content-annotator/pull-requests/9/overview
* tested in XP, works 
* try it on an v1-annotations-rw machine: curl -H "X-Request-Id: 123" localhost:32801/content/d798715a-e08d-11e5-bd34-4c13bb3472e1/annotations

Bumping content annotator to v18

---

services.yaml

This version will give us back correctly all the v1 annotations. (tested in xp)

Update public-annotations-api to v0.0.4 - returning v1 annotations.

---

services.yaml

Bump of content-rw-neo4j version which pulls in the below changes
Financial-Times/content-rw-neo4j@9f9f9b2 
-  Added platformVersion property to IS_CLASSIFIED_BY relationships between content and v2 brands.
- content-rw-neo4j returns 204 when content has no body.

Add platform version to content brands relationships2

---

.gitignore
methode-content-importer@.service
services.yaml

The change to add the TRANSFORMER_PROXY environment variable was
previously missing from the content-importer service file. This branch
is for updating the content-importer only, so the value is not removed
from the ingesters at this point.

Re-promote content-importer v45, this time with service changes.

---

neo4j-read-blue-sidekick@.service
neo4j-read-red-sidekick@.service

This not ideal but it works. 
Neo4j/neo4j driver try to do all sorts of clever things and compute their own urls when they try to connect to neo using the Host header of the first response. This means that the 2nd request to neo4j will not go via vulcan. As a side-effect the app becomes unhealthy when the neo4j instance which the app initially connected to goes down. 
{ "TrustForwardHeader": true, "PassHostHeader": true } solves this problem and routes all the requests via vulcan.
The second problem, now that all requests go via vulcan is that the driver also overwrites the path it uses to connect: /__neo4j-read/db/data becomes /db/data. As a workaround neo4j-read-db was added.
As a conclusion neo4j and its driver don't play nice when you overwrite the Host header or rewriter the url …

Making sure neo4j driver always connects to neo4j via vulcan.

---

content-ingester-neo4j-blue@.service
content-ingester-neo4j-red@.service
content-ingester@.service
services.yaml
wordpress-image-mapper-sidekick@.service
wordpress-image-mapper@.service

Introduces the new Wordpress Image Mapper service. It listens to the Native Topic on Kafka for Wordpress payloads and extracts the Featured Image. It creates two messages on CmsPublicationEvents for ImageSet and ImageModel. The ingester whitelists are updated to allow publishing of the ImageSet and ImageModel for contentUris matching the wordpress image mapper.

WP Image Mapper

---

api-policy-component-sidekick@.service
content-public-read-preview-sidekick@.service
document-store-api-sidekick@.service
enriched-content-read-api-sidekick@.service
public-annotations-api-sidekick@.service
public-content-by-concept-api-sidekick@.service
public-organisations-api-sidekick@.service
public-people-api-sidekick@.service
public-things-api-sidekick@.service

Occasionally etcd takes longer then 1 second to consolidate values across the cluster and the backends drop out from vulcan:
```
ge &engine.ServerDeleted{ServerKey:engine.ServerKey{BackendKey:engine.BackendKey{Id:"vcb-public-people-api-1"}, Id:"1"}}, err: vcb-public-people-api-1 not found
ge &engine.ServerDeleted{ServerKey:engine.ServerKey{BackendKey:engine.BackendKey{Id:"vcb-public-people-api-2"}, Id:"2"}}, err: vcb-public-people-api-2 not found
```
With no backends available, vulcan returns `500`.
This ups the TTL to 10 seconds, having enough overlap where services no longer get dropped by the load balancer.

Up ttl for load testing

---

services.yaml

with fix for connection pileup and rephrase of critical to warning for low severity apps.

Bump aggregate-healthcheck to 1.0.7

---

api-policy-component-sidekick@.service
document-store-api-sidekick@.service
enriched-content-read-api-sidekick@.service
neo4j-read-blue-sidekick@.service
neo4j-read-red-sidekick@.service
public-annotations-api-sidekick@.service
public-things-api-sidekick@.service

We can't get rid of sidekicks yet because of the deployer. @tamas-molnar is updating deployer to be able to cope with missing sidekicks for sequential deployment.
Any thoughts before I implement the same chaneg for the rest of our read apis?

Making sure vulcan backends to not expire for public-annotations-api

---

services.yaml

Bump kafka-bridge to 11.0.2 removing validation of uuid, and partially for origin system id and transaction id.

removing validation of uuid, and partially for origin system id and transaction id

---

services.yaml

Reason: the changes has broken the metadata publish flow.

Revert to previous bridge version: v11 (containing uuid validation).

---

services.yaml

Looking at the commit history, the intermediate builds relate to Puppet
changes affecting UCS only.

Bump version of ingesters.

---

services.yaml

Includes @JuliaFernee's changes as well (0.17.1).
Both have been tested in lower environments (xp, dynpub).
Will be in pre-prod for the weekend.

pam: skip notification check 4 deletes if there is no previous notification for that content

---

services.yaml

This version of WPAT has got changes ;
- the conversion of the short links to FT content links.
- conversion of the <a> href.... </a> for blogs into FT content links.
- allowing of the blog posts without authors to get published in UPP.
- checks the links in the posts to find the content type in document store

WPAT convert links to ft content links

---

services.yaml

These are the two services that produce messages for the
CmsPublicationEvents topic. (There is no requirement to deploy them
together, but it is convenient).

Bump content-importer and WPIM versions.

---

publish-availability-monitor@.service
services.yaml

0.17.3-4 puppet-stuff
0.17.5 https://github.com/Financial-Times/publish-availability-monitor/pull/71
0.18.0 https://github.com/Financial-Times/publish-availability-monitor/pull/70
0.18.1 https://github.com/Financial-Times/publish-availability-monitor/pull/72
0.18.2 https://github.com/Financial-Times/publish-availability-monitor/commit/b1f82caf5be186cf0c6702acba9c5193a70316b8
Tested in xp & pre-prod

PAM: External content validation + running CMD in one process only

---

cms-kafka-bridge-ucs-test-sidekick@.service
cms-kafka-bridge-ucs-test@.service
cms-metadata-kafka-bridge-ucs-test-sidekick@.service
cms-metadata-kafka-bridge-ucs-test@.service
concept-suggestions-kafka-bridge-ucs-test-sidekick@.service
concept-suggestions-kafka-bridge-ucs-test@.service
services.yaml

With this change lower env clusters will automatically consume traffic from both UCS Test and Prod without any manual changes.
@yolandeleungFT @nwrigh please cherry-pick this onto team branches
@nwrigh @scott-ace-newton  You might want to follow the same pattern for the bridges you guys are about to add

Added bridges for UCS Test. These should be deployed in lower envs only.

---

services.yaml

Intermediate builds were related to FTPlatform migration only.

Bump api-policy-component version.

---

document-store-api-sidekick@.service

This fix will allow calls to the lists endpoint with query parameters without '/', such as `https://prod-uk-up.ft.com/lists?curatedTopStoriesFor=704a3225-9b5c-3b4f-93c7-8e6a6993bfb0`

Fixed sidekick@.service in order to accept query pararameters to lists endpoint

---

services.yaml
splunk-forwarder.service

Varnish has new log format that adds `User-Agent` and `Auth User` + switches
`Host` for `X-Forwarded-For`
Varnish changes here:
http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/pull-requests/22/overview
Logfilter changes: https://github.com/Financial-Times/coco-logfilter/pull/22
Update splunk forwarder service to user versions/check history before
pulling, etc
| env | date | 
|------|-------|
|xp   | Tue 14 Jun 09:03:40 BST 2016 |
|pre-prod| Tue 14 Jun 10:07:55 BST 2016|

New varnish and splunk forwarder

---

services.yaml

Changes include for the genres-rw-neo4j:
* Make all the alternative ids Identifier nodes
* Only use prefLabel
* Add build-info
* Update the RW for the new json model - coming out from the transformer

Update genres-rw to v1.1.0

---

document-store-api-sidekick@.service

needs manual removal
check this value is there
etcdctl get /vulcand/frontends/public-services-content/frontend
if so remove it
etcdctl rm /vulcand/frontends/public-services-content/frontend

remove the public-service front end that conflicts with cpr

---

services.yaml

+ adding `sequentialDeployment` flag
**Note**: there is no GUI support to ACK a service, you have to do it manually, as described in https://github.com/Financial-Times/aggregate-healthcheck/blob/master/README.md

Ack support for agg-hc

---

services.yaml

* tested in `semantic`, works as excepted
* merged to `xp` too, but since neo4j-backup isn't there it did nothing
* will only push to `pre-prod` for now, `prod` after the ice age

Whitelist neo4j backup

---

services.yaml

One instance per transformer should be enough, thus reducing memory/CPU usage and load on TME on startup.
Note: deployer doesn't pick up changes on counts.

Reduce metadata transformers count

---

neo4j-blue@.service
neo4j-red@.service

This is a small change that should prevent us from getting `OutOfMemoryError` crashes in the pre-prod environment. We're currently using the [the default](https://neo4j.com/developer/docker-2-x/) of 512MB; this increases heap to 1GB.
After the change, neo's `ps` output looks like this (`-D` flags moved to new lines for readability):
root         1 14.6  5.1 5144800 852412 ?      Ssl  13:18   0:30 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/lib/neo4j/lib/commons-lang3-3.3.2.jar:/var/lib/neo4j/lib/concurrentlinkedhashmap-lru-1.4.2.jar:/var/lib/neo4j/lib/jline-2.12.jar:/var/lib/neo4j/lib/lucene-core-3.6.2.jar:/var/lib/neo4j/lib/neo4j-codegen-2.3.1.jar:/var/lib/neo4j/lib/neo4j-consistency-check-2.3.1.jar:/var/lib/neo4j/lib/neo4j-consistency-check-legacy-2.3.1.jar:/var/lib/neo4j/lib …

Increase Neo4j memory to 1GB to prevent OOM errors

---

services.yaml

EOM::Story with "Financial Times" channel is valid for publication, so non-synthetic requests should be monitored.

Bump PAM version.

---

services.yaml

We had to release a temporary version of the org-rw that went through and handled all the parent organisations first. However this is the final version .
https://github.com/Financial-Times/organisations-rw-neo4j/releases/tag/0.2.0

Updated the version of the org-rw to be the final version

---

services.yaml

During a merge conflict the wrong version ended up in the org-rw (should be 0.2.0)
(Previous PR: https://github.com/Financial-Times/up-service-files/pull/687)

Fixed to the right version v0.2.0 of org-rw as mistakedly got removed

---

services.yaml

Fix the version number so that later merges for the service aren't picked up until desired.
The most recent Jenkins build was v13 so I tagged the Docker image as such (I am not sure why it wasn't already tagged, in Jenkins it looks like it should be). The intended effect of this PR is in fact "no change".

Fix version of mongo-backup service.

---

services.yaml

Switch to passive consumer healthcheck; don't throw InterruptedException on normal shutdown.

Bump WPIM version.

---

services.yaml

No failover predicate by default which means no retries on error
https://github.com/Financial-Times/vulcan-config-builder/pull/17

Vulcan config builder v1.3.0 

---

aggregate-healthcheck-sidekick@.service

Varnish routing: http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/browse/default.vcl#22
Tested in XP

Removed unused frontends. Varnish is doing this routing.

---

mongodb-configurator.service
mongodb-sidekick@.service
mongodb@.service
neo4j-blue-sidekick@.service
neo4j-blue@.service
neo4j-read-blue-sidekick@.service
neo4j-read-red-sidekick@.service
neo4j-red-sidekick@.service
neo4j-red@.service
services.yaml

Fixing "container already in use" and "port not being set" issues for persistence units.
(See https://jira.ft.com/browse/UPP-1385 and https://jira.ft.com/browse/UPP-1390 for more details.)
Some service file refactoring was also made.
Tested in XP.
:warning: Note: these changes will require failover while deploying

Unique container names persistence units

---

services.yaml

Upgrade vulcan config builder to v1.3.1 which contains better logging
when invalid servers are discovered in backends.
UPDATE: Upgraded to version v1.3.2, supporting custom Host along with path regex https://github.com/Financial-Times/vulcan-config-builder/releases/tag/v1.3.2

Upgrade vulcan config builder

---

services.yaml

Annotation API errors will no longer cause the Enriched Content API to
error, it will just return an empty array

Decouple annotations API errors from enriched content API

---

services.yaml

Allows the fleet-unit-healthcheck to whitelist `mongo-backup@.service`. Tested in dynpub,

Fleet unit hc whitelist regex

---

services.yaml

Switch back in prod to the version of fleet-unit-healthcheck that will be healthy for the singleton mongo-backup service.

Revert fleet-unit-healthcheck version.

---

services.yaml

Intermediate build numbers were all broken builds.
See
http://git.svc.ft.com/projects/CP/repos/api-policy-component/pull-requests/76/overview

Restrict alt titles according to policy.

---

organisations-rw-neo4j-blue@.service
organisations-rw-neo4j-red@.service

Put org r/w apps to the same machines as their neo4j instances.
Whether to put these on the same machine as neo4j is a tradeoff.
Using a different machine reduces resource contention, and using the
same machine reduces inter-vm networking.
I have ovserved that the ingests go slowly when on different vms, and
putting them on the same machine makes things significantly faster.
In practice, resource contention on the neo4j machine is mininal because
the org r/w app uses very little memory of CPU.

Pin org r/w apps to corresponding neo instances.

---

mongo-backup.service
services.yaml

- Deploy fleet-unit-healthcheck 1.0.7 to allow whitelisting of multiple mongo-backup service instances.
- Remove "type=oneshot" from mongo-backup so that it is listed as "active" rather than "activating" when running, so that normal operation doesn't trigger a warning in the fleet-unit-healthcheck.

Fleet unit hc mongo backup

---

services.yaml

The brands UPPIdentifiers needed to be written when the content comes in with an unknown brand. Additionally I have also done the changes to use the new neoutils package. More details here: https://github.com/Financial-Times/content-rw-neo4j/pull/8

Bumped the version for the content-rw to create the brand identifiers

---

mongo-backup.service
services.yaml

Use newer version which uses newer Go version and had simplified code,
both of which reduce CPU overhead.
Also, limit memory to 1g in the docker command.

Lower resource usage by mongodb backup

---

api-policy-component@.service
services.yaml

The latest build of api policy component passes an env variable in the docker file. This commit sets that value.

Add configurable timeout to api policy component

---

coreos-version-checker-sidekick.service
coreos-version-checker.service
services.yaml

Remove CoreOS version check from system healthchecks, and add it as a separate app. 
Look for the code changes [here](https://github.com/Financial-Times/coco-system-healthcheck/pull/38) and [here](https://github.com/Financial-Times/coreos-version-checker).
Tested in xp.

Separate CoreOS version check from system healthcheck.

---

services.yaml

This release adds mongodb-online-backup to the timer service whitelist.

Upgrade to fleet unit healthcheck 1.0.8

---

services.yaml

This version of APC allows us having request statistics for /concordances and /things endpoints in Grafana. 
Tested in XP.

Extend api-policy-component with request metrics

---

aggregate-healthcheck-sidekick@.service
api-policy-component-sidekick@.service
content-public-read-preview-sidekick@.service
content-public-read-sidekick@.service
document-store-api-sidekick@.service
enriched-content-read-api-sidekick@.service
methode-article-transformer-sidekick@.service
public-annotations-api-sidekick@.service
public-concordances-api-sidekick@.service
system-healthcheck-sidekick.service

Add categories for concordances, enrichedcontent and content-read flows, which will be used by the public endpoints' dashing tiles.
Tested in XP.
You could check the categories on:
{env-url}/__health?categories=content-read
{env-url}/__health?categories=enrichedcontent-read
{env-url}/__health?categories=concordances-read

Extend read categories

---

content-public-read-preview-sidekick@.service
methode-article-transformer-sidekick@.service

ETCD keys for methode-article-transformer will need to be manually deleted.
Tested in XP.

Remove public-read-preview from content endpoint read categories.

---

services.yaml

Reconnect is enabled
Exe has been renamed to repo name.
Also, here are probably all the pull requests going into this release:
Financial-Times/content-rw-neo4j#10
Financial-Times/financial-instruments-rw-neo4j#3
Financial-Times/industry-classifications-rw-neo4j#8
Financial-Times/topics-rw-neo4j#4
Financial-Times/alphaville-series-rw-neo4j#8
Financial-Times/genres-rw-neo4j#6
Financial-Times/subjects-rw-neo4j#5
Financial-Times/special-reports-rw-neo4j#4
Financial-Times/sections-rw-neo4j#5
Financial-Times/roles-rw-neo4j#7
Financial-Times/organisations-rw-neo4j#17
Financial-Times/memberships-rw-neo4j#7
Financial-Times/locations-rw-neo4j#4
Financial-Times/content-rw-neo4j#9
Financial-Times/brands-rw-neo4j#8
Financial-Times/neo-utils-go#18
Financial-Times/neo-utils-go#17 …

Upgrade to Go apps using Neo4j

---

neo4j-blue@.service
services.yaml

Updating the blue Neo4J to 2.3.7. We have split them into two PR's so that we don't need to do a ZDD

Updated Neo4J to 2.3.7 - BLUE ONLY

---

api-policy-component@.service

Load tests show that performance does not degrade with new memory options. The service still handles around 270 req/s and the 99th pct is bellow 350 ms.

Added JAVA_OPTS restricting memory usuage of api-policy-component

---

load-replicator-sidekick@.service
load-replicator@.service
services.yaml

Added initial version of the load-replicator that tries to replicate the production load in a lower environment (pre-prod in this case).
https://github.com/Financial-Times/load-replicator
read load in xp: http://grafana.ft.com/dashboard/db/coco-api-policy-component-response-metrics?from=now-24h&to=now&var-environment=xp&var-node=All
read load in prod-uk: http://grafana.ft.com/dashboard/db/coco-api-policy-component-response-metrics?from=now-24h&to=now&var-environment=prod-uk&var-node=All

Added load-replicator 1.0.0

---

services.yaml

Set version to newly released v0.1.0, which has no changes from the
current "latest" version in use.

Use a fixed version of mongodb-configurator

---

burrow-sidekick@.service
burrow@.service
kafka-lagcheck-sidekick@.service
kafka-lagcheck@.service
services.yaml

https://github.com/Financial-Times/kafka-lagcheck
https://github.com/Financial-Times/burrow
https://github.com/Financial-Times/pub-service-files/pull/55
* Allowed lag is set to 30 currently.
* Concept is an ignored partition.
* Burrow can show partitions in unhealthy state even if lag is less than 30, if it is seeing the stalled or stopped. (https://github.com/linkedin/Burrow/wiki/Consumer-Lag-Evaluation-Rules) These are special cases, we'll need to see this lagcheck running in live, and see its behaviour during a mass publish.
* Can be acked any time.
* Memory limit on both apps: 256MB
* Present in xp, pub-xp, pub-pre-prod-uk, pre-prod-uk

introducing kafka-lagcheck

---

services.yaml

Currently, 404s produce huge amounts of logging due to an unnecessary stacktrace; this is now suppressed (now at DEBUG level).

Reducing DSAPI Logging

---

neo4j-read-blue-sidekick@.service
neo4j-read-red-sidekick@.service
services.yaml

Since the user agent was changed in neoutils to describe the exe making the call (eg. "**public-people-api (using neoutils)**"),  the vulcan rewrite rule for public reads hasn't been working correctly on connection.

Allow vulcan to recognise the new user-agent

---

services.yaml

Bumping elb-dns-registrator to v4.0.1 and tunnel-registrator to v1.0.1 to update DNS TTL values to 30s.

Updating DNS service versions to update TTLs to 30s

---

splunk-forwarder.service

This release bumps coco-splunk-http-forwarder version to v0.0.7 (https://github.com/Financial-Times/coco-splunk-http-forwarder/pull/7). 
v0.0.7 provides Graphite integration. Example graphs are available here: http://grafana.ft.com/dashboard/db/coco-xp-delivery-coco-splunk-http-forwarder-stats

splunk-forwarder -> graphite integration

---

services.yaml
varnish@.service

Please also review the new repo [here](https://github.com/Financial-Times/delivery-varnish) for delivery varnish - it should be functionally the same as the [bitbucket](http://git.svc.ft.com/projects/CP/repos/api-component-policy-varnish/browse) version.

Migrating BitBucket varnish to Github

---

splunk-forwarder.service

Bump splunk-forwarder version to v0.0.8 (https://github.com/Financial-Times/coco-splunk-http-forwarder/releases/tag/v0.0.8) to increase workers from 8 to 12.

12 workers for splunk forwarder

---

splunk-forwarder.service

This branch upgrades splunk-forwarder service to version 1.0.0 which includes implementation for Splunk HEC client. 
This release no longer connect to splunk-forwarder cluster but instead sends events directly to Splunk Cloud.

splunk-forwarder: Switch to Splunk HTTP Event Collector

---

services.yaml

Automatically raise CRs when deleting DNS records via Konstructor.
Currently uses my own email address due to limitations in Salesforce - have requested a service account to be set up so that we can use a group email instead, but that might take a week or longer.

Update DNS services to automagically raise CRs

---

kafka.service

* see https://docs.google.com/document/d/1d21pm21vOCxNqrglCLzNj-Mr0xrnMc6gqZS0V-zse90/edit#
* tested in delivery XP, works with the appropriate userdata changes
:bangbang:**only merge AFTER this change: https://github.com/Financial-Times/coco-provisioner/pull/135 is applied to delivery clusters!** :bangbang:

Talk to the docker daemon on a host:port rather than a socket

---

services.yaml

- see PR http://git.svc.ft.com/projects/CP/repos/binary-ingester/pull-requests/40/overview 
- versions between 92 and 97 are DH fails, no changes
- tried in XP, still works

Upgrade binary-ingester to v97

---

services.yaml

When provisioning a new cluster this component's healthcheck was checking if a topic was present which was unnecessary for this component and created noise
https://github.com/Financial-Times/concept-ingester/pull/15

Bumping version of the concept ingester to remove topic check in healthcheck

---

services.yaml

Allow organisations v1 major mentions to come through from TME/QMI
https://github.com/Financial-Times/v1-suggestor/pull/21

Bumped the version to include the addition of the v1 org metadata

---

services.yaml

Added major mentions so V1 organisation annotations can also be surfaced in enrichedcontent
https://github.com/Financial-Times/public-annotations-api/pull/11

Adding Major Mentions to the public annotations-api

---

services.yaml

http://git.svc.ft.com/projects/CP/repos/wordpress-article-transformer/commits/238e5e380ec8cd2227cf3e6f933ed448addbd8d5

Removed coupling to apiUrl for WP articles

---

rec-reads-content-annotator-sidekick@.service
rec-reads-content-annotator@.service
services.yaml

Adding Recommended Reads content annotator to coco clusters as we migrate suggestions flow from non-coco. This service will read ConceptSuggestions topic and send annotations to rr-suggestions-indexer in ftp2 via varnish and elb.

Add rec reads content annotator

---

services.yaml

Fixed orphan container problem for mongo-backup. Changes can be found here: https://github.com/Financial-Times/coco-mongodb-backup/pull/16

Fixed orphan container problem for mongo-backup

---

public-six-degrees-api-sidekick@.service
public-six-degrees-api@.service
services.yaml

See https://github.com/Financial-Times/public-six-degrees/releases/tag/1.0.0 - "productionized" app
Manual steps after deployment:
```
etcdctl rm --recursive /ft/healthcheck/public-six-degrees-1
etcdctl rm --recursive /ft/healthcheck/public-six-degrees-2
etcdctl rm --recursive /ft/services/public-six-degrees
``` 
Sometimes `aggregate-healthcheck` fails to read etcd value changes (don't know why), so a restart of that might needed
Tested in XP.

Renamed public-six-degrees to public-six-degrees-api. Bump version

---

notifications-rw@.service
services.yaml

PR for dynpub. See
http://git.svc.ft.com/projects/CP/repos/notifications-rw/pull-requests/52/overview. Wait a maximum of 1s more than the cache max-age before forcing shutdown.

Delay shutdown of notifications-rw for deferred writes.

---

notifications-push@.service
notifications-rw@.service

Stopping `notifications-push` has not been working since `list-notifications-push` was deployed. It turns out that container filtering in case of overlapping unit names is not restrictive enough.
The same could happen with `notifications-rw` if `list-notifications-rw` runs on the same machine.
This could happen with any new overlapping unit name.

notifications: fix units' stop cmd

---

services.yaml

See 
- https://github.com/Financial-Times/delivery-varnish/pull/5
- https://github.com/Financial-Times/delivery-varnish/pull/6
Tested in XP, works: `https://xp-up.ft.com/concept/search -d {"term":"London"}` + basic auth

Adding routing for Concept Search API + purge method

---

content-preview@.service

* remember to create the keys in existing environments, pre-prod, prod-uk, prod-us - `etcdctl set /ft/config/methode-api https://...`
Goes with https://github.com/Financial-Times/coco-provisioner/pull/161

Methode api etcd

---

services.yaml

Using 200 instead of 202 - for ingester to accept.

Update concept-rw-elasticsearch to v0.0.10 - consistent status codes

---

services.yaml

and conflict resolution gets pushed through
https://github.com/Financial-Times/public-concordances-api/pull/5

Bumped the version to ensure all the code from recent merges 

---

services.yaml

as there is a bug with 20 that means that no annotations are returned if the brands have no parents ie. if only has FT as brand as all other brands have FT as their parent

Rolled back to version 19 

---

services.yaml

Fix for issue where content only has a parent brand.
https://github.com/Financial-Times/public-annotations-api/pull/14

Bump public-annotations-api to v0.0.21

---

splunk-forwarder.service

This [commit](https://github.com/Financial-Times/publish-availability-monitor/commit/41a5fa252ab16414094c8a5951d823c323b29bc8) improves PAMs transaction ID generation, so it's clear which publish is being monitored for each request. 
A side-effect is that we need to remove the character restrictions for PAM txids in the logfilter.

Improve log filter for PAM TIDs

---

content-ingester-sidekick@.service

This is a well know issue regarding services that contains substrings of other service names.

Fixed sidekick for content-ingester

---

neo4j-blue@.service
neo4j-red@.service

Disabled the timeout logic for killing processes to avoid corruption of the datastore due to systemd killing the Neo instance. The systemd default is 90s before it issues a SIGKILL and the datastore may have grown just enough that it takes longer than 90s. Setting to infinity allows the service to shutdown in its own time and so a nasty shutdown and subsequent corruption should be avoided
http://unix.stackexchange.com/questions/227017/how-to-change-systemd-service-timeout-value

Disabled the timeout logic for SystemD killing Neo4J

---

rec-reads-content-annotator@.service
services.yaml

New suggestions endpoint that we can reload annotations from cache rather than going around the whole content cycle
http://git.svc.ft.com:8080/projects/CP/repos/content-annotator/pull-requests/26/overview

Add suggestions endpoint to content annotator

---

methode-image-binary-mapper@.service

This change should prevent the prod issue that we had to publish big images.

Increased memory for methode-image-binary-ingester due to prod issue

---

services.yaml

v1.0.13 contains the build-info fix from v1.0.12, but not the other
changes that were present in v1.0.11. See
https://github.com/Financial-Times/methode-article-mapper/pull/11

MAM version change.

---

services.yaml

As decided with Sarah, the internal component topper will expose the label backgroundColour label instead of bgColor.
https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/6

Internal components mapper, changed bgColor label to backgroundColour 

---

services.yaml

New Varnish version which has request limit set for internalcontent-preview
https://github.com/Financial-Times/delivery-varnish/pull/9

Varnish version bump to 0.1.7

---

services.yaml

https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/7
methode-article-internal-components mapper should return 404 when the article doesn't contain internal components, instead of 422.

Internal components mapper fix.

---

services.yaml

The `deferred write` log line had an incorrect MDC transaction id, which could cause confusion.

Fixing MDC bug

---

services.yaml

Same change applied to several services:
https://github.com/Financial-Times/methode-image-binary-mapper/pull/3
https://github.com/Financial-Times/methode-image-model-mapper/pull/5
https://github.com/Financial-Times/methode-image-set-mapper/pull/3
https://github.com/Financial-Times/wordpress-article-mapper/pull/14
Tested in `xp`.

Fix the mapper's /build-info endpoint & panic guide urls

---

services.yaml

Re-releasing alongside the fix to PAM which is [here](https://github.com/Financial-Times/pub-service-files/pull/185).

Content Placeholders should be saved as "Content" Notifications

---

methode-content-collection-mapper@.service

Changed the docker hub repo name of methode-content-collection-mapper (from previous methode-story-package-mapper): https://hub.docker.com/r/coco/methode-content-collection-mapper/
The old one is here: https://hub.docker.com/r/coco/methode-story-package-mapper/
Both repos are currently up, I will remove the old one once this is merged to PROD:

Renamed content collection mapper repo name.

---

services.yaml

`/enrichedcontent` not to surface `contains` and `containedIn` fields for B2B clients
* https://github.com/Financial-Times/api-policy-component/pull/12
tested in rj

`/enrichedcontent` not to surface `contains` and `containedIn` fields for B2B clients

---

services.yaml

https://github.com/Financial-Times/concept-search-api/pull/18
- Added vendoring to the concept-search-api
- Fixed a healthcheck bug

Increased concept-search-api version to v1.0.7

---

services.yaml

... the same way in HTTP POST as from kafka. Log warn but goes silently.
http://git.svc.ft.com/projects/CP/repos/concept-suggestion-api/pull-requests/26/overview

concept-suggestion-api v36 - empty bodies are treated

---

services.yaml

https://github.com/Financial-Times/methode-article-mapper/pull/23

bumped MAM to version that supports empty body for content packages

---

services.yaml

Added gtg endpoints for:
- internal-content-api https://github.com/Financial-Times/internal-content-api/pull/13
- internal-content-preview-api https://github.com/Financial-Times/internal-content-api/pull/13
Fixed headers for:
- list-notifications-rw https://github.com/Financial-Times/list-notifications-rw/pull/21

Added gtg endpoints for list-notifications-rw and internal-content-api

---

services.yaml

Added GTG endpoints for the following services:
- synthetic-image-publication-monitor [https://github.com/Financial-Times/coco-synthetic-image-publication-monitor/pull/17](url)
- content-public-read-preview [http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/37/overview](url)
- content-public-read [http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/37/overview](url)
- methode-article-internal-components-mapper [https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/11](url)

Added gtg endpoints for SIPM, MAICM and content public read services

---

services.yaml

Add new endpoint for public-annotations-api `/content/{uuid}/annotations/{platformVersion}`. 
Note: the returned annotation model contains more fields than the usual /annotations one - it includes identifiers as well.
Details: https://github.com/Financial-Times/public-annotations-api/pull/16
Tested in XP.

Add new endpoint for public-annotations-api.

---

services.yaml

https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/12

bumped MAICM to version with removed deprecated content fields

---

services.yaml

Added gtg endpoints for:
- content-preview https://github.com/Financial-Times/content-preview/pull/20
- internal-components-preview https://github.com/Financial-Times/content-preview/pull/20
- wordpress-article-mapper https://github.com/Financial-Times/wordpress-article-mapper/pull/13
- concept-suggestion-api http://git.svc.ft.com/projects/CP/repos/concept-suggestion-api/pull-requests/25/overview

Added gtg endpoints for content-preview and wordpress-article-mapper

---

services.yaml

This PR is to deploy the bridges between `pub-pre-prod` and `pre-prod` clusters only.
The change is implemented in this PR: https://github.com/Financial-Times/coco-kafka-bridge/pull/40

kafka-bridge that supports native hash pre-prod only

---

services.yaml

- decreased the timeouts and number of retries that enriched-content-read-api makes when accessing content-api, relations-api and annotations-api
http://git.svc.ft.com/projects/CP/repos/enriched-content-read-api/pull-requests/31/overview

Enrichedcontent should respond in a timely manner

---

services.yaml

- Changes to support embedded videos in WP that are published in Next Video Editor
- Documentation can be seen here:
https://docs.google.com/a/ft.com/document/d/1ioJCmasEN2unBFnr1QcGj6Cf-QE0NKtgE2YVNYL3lVM/edit?usp=sharing
- App PR (approved & merged): https://github.com/Financial-Times/wordpress-article-mapper/pull/16

  Wordpress Article Mapper: Support embedded videos from Next Video Editor 

---

services.yaml

Support will be provided for embedded videos within:
- videoplayer element with both ID types: UUID (from Next Video Editor) and old Brightcove (from old Methode articles)
- content element with hyperlinks to Next video
Tested on video cluster
Service PR: https://github.com/Financial-Times/methode-article-mapper/pull/26
See documentation for Methode articles embedded videos handling:
https://sites.google.com/a/ft.com/universal-publishing/documentation/story-specs/3-mar-2017-next-video-platform-work

Next videos embedded within Methode articles

---

services.yaml

https://github.com/Financial-Times/coco-system-healthcheck/pull/43
sys-hc now has PID 1 in the container:
```
[~][14:57:43][xp][]$ fcssh 6550b6d5 docker exec -ti c0364c820669 sh -c ps
PID   USER     TIME   COMMAND
1 root       0:00 /coco-system-healthcheck
[~][14:58:06][xp][]$ fcssh b4c41cd7 docker exec -ti 6d6e246604dc sh -c ps
PID   USER     TIME   COMMAND
1 root       0:00 /coco-system-healthcheck
[~][14:58:22][xp][]$ fcssh ce564685 docker exec -ti a075c90e5613 sh -c ps
PID   USER     TIME   COMMAND
1 root       0:00 /coco-system-healthcheck
[~][14:58:42][xp][]$ fcssh f064489d docker exec -ti 0a6be88ca23c sh -c ps
PID   USER     TIME   COMMAND
1 root       0:00 /coco-system-healthcheck
[~][15:04:50][xp][]$ fcssh f33043f9 docker exec -ti 7f9dd240e31a sh -c ps
PID   USER     TIME …
```

Update sys-hc to version which contains pid 1 fix

---

services.yaml

See PR from [here](https://github.com/Financial-Times/coco-synthetic-image-publication-monitor/pull/18), and the [task details](https://trello.com/c/iyzTw3sx) on the OpsCop board.

Increase check period for synthetic image publishes.

---

services.yaml
v1-annotations-rw-neo4j@.service
v2-annotations-rw-neo4j@.service

Version 0.2.0 to be used for all services which have annotations-rw as a code base: https://github.com/Financial-Times/annotations-rw-neo4j/releases/tag/0.2.0
This contains @david-smith-ft's changes as well: https://github.com/Financial-Times/annotations-rw-neo4j/pull/18
NOTE: Except **brightcove-annotations-rw-neo4j** which will be decommissioned soon

Aligned version for annotations-rw services

---

services.yaml

MAM: https://github.com/Financial-Times/methode-article-mapper/pull/27
MCPM: https://github.com/Financial-Times/methode-content-placeholder-mapper/pull/11
MAICM: https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/15
CPR: http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/40/overview

Content package title override and dummy text removal

---

kafka-lagcheck@.service
services.yaml

This is meant to suppress warnings from prod kafka-lagcheck caused by consumers (kafka-bridges) from lower envs.
PR for kafka-lagcheck changes: https://github.com/Financial-Times/kafka-lagcheck/pull/3

Filtering unrelated kafka bridges from healthchecks

---

next-video-content-collection-mapper-sidekick@.service
next-video-content-collection-mapper@.service
services.yaml

- New service that will handle `related` videos as story package items
- Architecture diagram: see https://sites.google.com/a/ft.com/universal-publishing/documentation/story-specs/3-mar-2017-next-video-platform-work
- Release candidate: https://github.com/Financial-Times/upp-next-video-content-collection-mapper/releases/tag/1.0.0

Handle story package for videos (upp-video-content-collection-mapper)

---

services.yaml

[PR](https://github.com/Financial-Times/content-rw-elasticsearch/pull/4)
Tested in XP.

Minor content-rw-elasticsearch service fixes - version 1.0.2

---

services.yaml

Improve content-rw-elasticsearch logging + generating image uuids using the uuid-utils library.
[PR](https://github.com/Financial-Times/content-rw-elasticsearch/pull/6)
Tested in XP

Improve content es indexer logging

---

services.yaml

- Propagate TID if given as a request header for the post-publication-combiner force endpoint. [[PR]](https://github.com/Financial-Times/post-publication-combiner/pull/5)
- Overwrite the publishReference field in ES with the actual transaction id, instead of the content's publishRef value. [[PR]](https://github.com/Financial-Times/content-rw-elasticsearch/pull/7)
~ Tested in XP.

ES content indexing - propagate TID

---

mongodb-configurator.service

- upp2-188
- this change handles the case when the mongo configurator reads invalid data from etcd: instead of failing and stopping when it encounters and unreacheable mongo, it will fail and be restarted so it can retry

Make mongo-configurator a simple service, and add restart condition

---

services.yaml

Improved kafka lagcheck to use burrow status in order to determine if it should be warning for a specific consumer group.
Codebase PR: https://github.com/Financial-Times/kafka-lagcheck/pull/5

Improved kafka lagcheck to use burrow status

---

mongodb@.service

- this will allow mongodb ample time to shut down gracefully before being forcefully terminated
- for more details see UPP2-198
- this change *WILL* restart the mongos

Increase mongo stop grace period

---

services.yaml

Media type for videos has been changed from `MediaResource` to `Video`. The following services are affected:
- [upp-next-video-mapper ](https://github.com/Financial-Times/upp-next-video-mapper/releases/tag/1.3.2)
- [methode-article-mapper](https://github.com/Financial-Times/methode-article-mapper/releases/tag/1.1.3)
- [content-rw-neo4j](https://github.com/Financial-Times/content-rw-neo4j/releases/tag/1.0.4)
- [content-public-read](http://git.svc.ft.com:8080/projects/CP/repos/content-public-read/pull-requests/47/overview)
Tested in `video` cluster

Type for videos: changed from MediaResource to Video

---

services.yaml

Due to Splunk Cloud license limits, this disables the Splunk Forwarder on a temporary basis for the `pre-prod` environments until we can get more permanent code changes out.

Disable Splunk Forwarder

---

services.yaml

Wordpress Article Mapper: [PR](https://github.com/Financial-Times/wordpress-article-mapper/pull/18)
Api Policy Component: [PR](https://github.com/Financial-Times/api-policy-component/pull/22)

Use post url as webUrl for wordpress blogs

---

services.yaml

Fields for image rights from Methode: mapped, stored and exposed in CAPI.
Tested in `video` cluster. Services affected:
- [methode-image-model-mapper](https://github.com/Financial-Times/methode-image-model-mapper/pull/11)
- [content-public-read](http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/46/overview)
- api-policy-component: [this](https://github.com/Financial-Times/api-policy-component/pull/19) and [this](https://github.com/Financial-Times/api-policy-component/pull/21)

Image rights feature

---

services.yaml

Please see http://git.svc.ft.com/projects/CP/repos/content-public-read/pull-requests/48/overview
Tested in team clusters, works as expected

CPR not logging HTTP 404s as errors with stacktraces

---

splunk-forwarder.service

Blacklisting `/__health` and `/__gtg` entries in coco logfilter, in order to temporary reduce the logging volume (OpsCop initiative).
App PR: https://github.com/Financial-Times/coco-logfilter/pull/34
How many events will be ignored after releasing this change?
*  `__health` ≈ 26k events/min
* `__gtg` ≈ 450 events/min
_(stats extracted for Prod, representing the total number of entries for both us + uk)_

Logfilter reduce logging volume (blacklist health & gtg events)

---

services.yaml

- `canBeDistributed` field set to `yes` by default as for image sets from Methode (see http://git.svc.ft.com/projects/CP/repos/wordpress-image-mapper/pull-requests/19/overview)

Image rights work for WIM for consistency

---

services.yaml

This is due to changes in the base app
https://github.com/Financial-Times/organisations-rw-neo4j/pull/29
https://github.com/Financial-Times/content-rw-neo4j/pull/23

Added transaction id to content and organisations -rw

---

services.yaml

This is about onward journey being allowed on the /internalcontent and /internalcontent-preview and strip out on the other endpoints (for B2B customers).
Codebase PR: 
https://github.com/Financial-Times/api-policy-component/pull/20
https://github.com/Financial-Times/methode-article-mapper/pull/31

Onward journey

---

services.yaml

Upgrade of concept search api after this bugfix:
https://github.com/Financial-Times/concept-search-api/pull/36

Bugfix to concept-search-api boost param error

---

services.yaml

This adds the in article layout component (along with in-article recommended component which is in MAM now, and will be reverted) and all the MAM body processing, in order to have the body duplicated for internal components flow.
Codebase PR: https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/16

Release version for in-article layout component.

---

new-notifications-push@.service
services.yaml

Notifications Push service will be able to connect directly to Kafka, without using Kafka Proxy.
- App changes: https://github.com/Financial-Times/notifications-push/pull/46

Notifications push - remove Kafka proxy

---

public-annotations-api@.service
public-concordances-api@.service
services.yaml

This release is to support the new concordance model that we are initially using for managing curated brands within smartlogic
1. Content-By-Concept: https://github.com/Financial-Times/public-content-by-concept-api/pull/10
2. Annotations API: TO BE DONE
3. Things API: https://github.com/Financial-Times/public-things-api/pull/6
4. Concordances API: https://github.com/Financial-Times/public-concordances-api/pull/12
4. Brands API: https://github.com/Financial-Times/public-brands-api/pull/12

Release for Public Read APIs to support new concordance model

---

list-notifications-push@.service
services.yaml

changes:
- https://github.com/Financial-Times/notifications-push/pull/46 : Notifications Push service will be able to connect directly to Kafka, without using Kafka Proxy.
- https://github.com/Financial-Times/notifications-push/pull/45 Updated list-notifications-push to use apiKeys
**Note**: this should be released only after https://github.com/Financial-Times/pub-service-files/pull/290 is released. Also clients should already be using apiKeys when this change is released to prod

Updated list-notifications-push to use apiKeys

---

services.yaml

codebase changes:
https://github.com/Financial-Times/wordpress-article-mapper/pull/19

Added scoop flag to WAM

---

services.yaml

- Changing `new-notifications-push` to contain Title and Scoop fields in notifications body
- App changes: https://github.com/Financial-Times/notifications-push/commit/989fc921eeadb9a082ab611931cdf9f432a276b7

Adding Title and Scoop fields to Notifications Push

---

load-replicator@.service

Currently load-replicator sends traffic to the cluster address (eg, `pre-prod-uk-up.ft.com`), which doesn't simulate failovers correctly.
This change sends all load-replicator traffic via the GLB `pre-prod-up.ft.com` address.

Use GLB address for load-replicator

---

load-replicator@.service

Because it's one long single line that starts up the service, I think it just accidentally comments out half of the startup command.

Removing comment, deployer / service file doesn't like it

---

services.yaml

* https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/22
* https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/21
Mapping the new in-article component called summary that servers for summarizing the key points of an article.
The model in short:
```json
{
"bodyXML": "<body><p>Some text here</p></body>",
"summary": {
"bodyXML": "<body><p>Some other text here</p></body>"
},
}
```
[RJ trello card](https://trello.com/c/Thw5ZbAr/471-summary-component)
Transforming `<a>` tags into `<ft-content>` the correct way, setting its `type` attribute to correct FT types `Content`, `Article`, etc. Previously it was just hardcoded to `Article`.
[RJ trello card](https://trello.com/c/Gz57WuTV/124-rework-xml-tags-from-recommended)

Summary component and ft-content

---

services.yaml

There was an issue that if given ids from types that are the old model along with ids that have the new model then not all the results were returned.  Loads of sirupsen fixes were needed also
Main PR:
https://github.com/Financial-Times/public-concordances-api/pull/18 
Sirupsen fixes:
https://github.com/Financial-Times/annotations-rw-neo4j/pull/27
https://github.com/Financial-Times/content-rw-neo4j/pull/25
https://github.com/Financial-Times/organisations-rw-neo4j/pull/32

Multiple ids issue fix for public concordance api

---

new-notifications-push@.service
services.yaml

These changes will affect **_new-notifications-push_** service. Clients can filter the content adding a request param for content type (e.g. https://api.ft.com/content/notifications-push?type=article)
- If the type is not specified, the filter will be set to `type=Article`
- Clients can specify `type=All` that will return all supported notifications, including CPHs.
- `DELETE` notifications will be always sent to the clients, because their payload is empty (in Kafka) and we cannot extract the type
- If the client specifies an invalid type, a client error is returned
- App changes: https://github.com/Financial-Times/notifications-push/pull/50 && https://github.com/Financial-Times/notifications-push/pull/51

Allow push clients to specify type, default to 'only articles'

---

services.yaml

Concorded brands were being duplicated because the query got confused when looking for parents.
https://github.com/Financial-Times/public-annotations-api/pull/29

Public Annotations API - Fix brand duplication

---

services.yaml

https://github.com/Financial-Times/document-store-api/pull/5
contains also k8s helm migration
https://github.com/Financial-Times/document-store-api/pull/3
document-store-api:1.0.3-getmultiplebypost-rc1 - able to retrieve items by HTTP POST including an ["array", "of", "uuids"]

able to retrieve items by HTTP POST including an ["array", "of", "uuids"]

---

services.yaml

These private services have been rebuilt on CircleCI, and pushed to Nexus.
We're rebuilding and redeploying to ensure that we're not using a potentially compromised image in our clusters.

Redeploying private services

---

cms-kafka-bridge-pub-prod-uk@.service
cms-kafka-bridge-pub-prod-us@.service
cms-metadata-kafka-bridge-pub-prod-uk@.service
cms-metadata-kafka-bridge-pub-prod-us@.service
concepts-kafka-bridge-pub-prod@.service
services.yaml

Will need to be updated with the final tagged version (after merging [this PR](https://github.com/Financial-Times/coco-kafka-bridge/pull/44)).

Add k8s bridge versions - without host header routing.

---

services.yaml

- bring version in sync with Kubernetes - update is from an old version but 1.55.1 was running in the pub cluster, for some reason this wasn't updated when the codebase changed, might need a closer look

Bring cms-notifier in sync with k8s and pub cluster

---

services.yaml

- helm config fix https://github.com/Financial-Times/wordpress-image-mapper/pull/3
- https://github.com/Financial-Times/wordpress-image-mapper/compare/0.55.0...0.56.0

Update wim to latest version, with helm integration fix

---

services.yaml

https://github.com/Financial-Times/methode-article-mapper/pull/39

methode-article-mapper:1.6.1 - Find the right git tag while building.

---

services.yaml

No code changes, only helm integration:
- https://github.com/Financial-Times/upp-next-video-mapper/compare/1.3.3...1.5.0
- https://github.com/Financial-Times/upp-next-video-mapper/pull/11
- https://github.com/Financial-Times/upp-next-video-annotations-mapper/compare/1.1.1...1.3.0
- https://github.com/Financial-Times/upp-next-video-annotations-mapper/pull/7
- https://github.com/Financial-Times/upp-next-video-content-collection-mapper/compare/1.1.0...1.3.0
- https://github.com/Financial-Times/upp-next-video-content-collection-mapper/pull/5

Update next-video-*-mappers to latest versions with helm integration

---

services.yaml

- Reduce logging and ensure transaction_id is logged for every request
- Upgrade to Dropwizard 1.x
- Remove ResilientClient, so this service no longer performs retries

Feature/api policy component logging retry dw1.x

---

services.yaml

- wordpress-article-mapper: https://github.com/Financial-Times/wordpress-article-mapper/pull/22

FastFT articles are now syndicatable by default

---

services.yaml

MAICM PR: https://github.com/Financial-Times/methode-article-internal-components-mapper/pull/27
Added 2 new fields to /internalcontent (internalcomponents collection):
- promotionalTitleVariant in alternativeTitles
- promotionalStandfirstVariant in alternativeStandfirsts
These fields are used for A/B testing.

Added promotional variant fields

---

services.yaml

Internal content placeholder complementarycontent has its brands set from the db content.
https://github.com/Financial-Times/methode-content-placeholder-mapper/pull/21

Fix complementarycontent brands

---

complementarycontent-ingester@.service
services.yaml

fixed complementarycontent-ingester's env vars and all ingesters to version 1.77.1-k8s-cleanup-rc1
https://trello.com/c/1MmRqXM0/131-image-resolver-to-handle-empty-lead-images-correctly-and-content-public-read-to-handle-empty-requests-gracefully
https://github.com/Financial-Times/ingester/pull/6

Ingester env vars cleanup

---

services.yaml

Release https://github.com/Financial-Times/generic-rw-s3/releases/tag/1.4.1
PR: https://github.com/Financial-Times/generic-rw-s3/pull/18

Helm config only: Added bucket region value for the S3 bucket

---

services.yaml

image-resolver:2.1.1-k8s-simplification-rc1 - no http call if no images to resolve + tid propagated
https://trello.com/c/1MmRqXM0/131-image-resolver-to-handle-empty-lead-images-correctly-and-content-public-read-to-handle-empty-requests-gracefully
https://github.com/Financial-Times/image-resolver/pull/8

image-resolver simplification

---

services.yaml

Using the pod name as the group name
PR: https://github.com/Financial-Times/notifications-push/pull/55

k8s fix: Make kafka group name unique

---

services.yaml

Original [PR](https://github.com/Financial-Times/cms-notifier/pull/9)
⚠️ This version of the repo doesn't have the video splitting activated anyway, this release is only required to have the same version of the app deployed in all the envs.
The service version will be updated once the changes are ready to go to pre-prod.

Have unique tids for video metadata in all envs. 

---

services.yaml

New version of `upp-exports`, containing helm changes (run k8s in parallel with CoCo)

UPP exports - k8s run in parallel

---

services.yaml

Helm config only: moved ces host to global config 
https://github.com/Financial-Times/concept-suggestion-api/releases/tag/1.47.1 
PR https://github.com/Financial-Times/concept-suggestion-api/pull/4

Releasing concept-suggestion-api 1.47.1

---

services.yaml

set hasHealthcheck flag to false in helm config to remove this service from k8s aggregate healthcheck: Financial-Times/burrow#4

Updated helm config for burrow

---

services.yaml

Added bridges from prod k8s to prod coco
Adjusted the default bridges from team clusters to go to prod k8s.
Fixes:
Bridging the the CMS pre native topics from publishing
Pointed CMS bridges to CMS notifier
Release link: https://github.com/Financial-Times/coco-kafka-bridge/releases/tag/15.0.3
PR: https://github.com/Financial-Times/coco-kafka-bridge/pull/47

Releasing bridges 15.0.3

---

services.yaml
upp-exports-rw-s3@.service

Tag: https://github.com/Financial-Times/concept-exporter/releases/tag/1.1.0
Needed for K8s work:
* healthcheck (max 10s)
* gtg check (max 3s)
* pod affinity
* memory limit and request
Also fixed healthcheck issues when exporting organisations and including https://github.com/Financial-Times/up-service-files/pull/1470

Concept exporter: updates for k8s

---

services.yaml

K8s: Increase memory limit to 1Gi for K8s
PR: https://github.com/Financial-Times/methode-article-mapper/pull/41
Release: https://github.com/Financial-Times/methode-article-mapper/releases/tag/1.6.3

Releasing methode article mapper 1.6.3

---

services.yaml

k8s: Increase memory limit to 1Gi for K8S
PR: https://github.com/Financial-Times/methode-list-mapper/pull/7
Release: https://github.com/Financial-Times/methode-list-mapper/releases/tag/1.2.1

Releasing methode list mapper 1.2.1

---

services.yaml

k8s: k8s: Increase memory limit to 256Mi for K8S
PR: https://github.com/Financial-Times/methode-article-image-set-mapper/pull/7
Release: https://github.com/Financial-Times/methode-article-image-set-mapper/releases/tag/1.4.1

Releasing methode article image set mapper 1.4.1

---

services.yaml

https://github.com/Financial-Times/coreos-version-checker/pull/8
- gtg endpoint
- gtg/health timeouts
- resource limits
- non-standard channel handling for K8S

coreos-version-checker-upgrade

---

load-replicator@.service
load-replicator@.timer

Start the service at 7AM on weekdays and does not run on weekends.
The service will be run for a certain duration (11 hours) to cover romanian and UK work timings.
Duration will be set as an etcd key
Tested the changes in the dynpub cluster. The service goes into a `inactive` state after the duration specified. So added restart `on-failure`.

Load replicator changes

---

services.yaml

- added memory request, lowered limit based on docker stats
- cleaned up helm config files
- switched to circleCI 2
- vendored dependencies
- updated hc library
- deleted unused checks
- removed check for port 8080, which is only needed for vulcan
https://github.com/Financial-Times/coco-system-healthcheck/pull/47

system-healthcheck improvements

---

services.yaml

https://github.com/Financial-Times/kafka-lagcheck/pull/8
tested in: xp, pre-prod, k8s del and pub clusters

kafka-lagcheck affinity

---

services.yaml

Adjusted bridges for k8s staging env.
Release link: https://github.com/Financial-Times/coco-kafka-bridge/releases/tag/15.1.1
PR: https://github.com/Financial-Times/coco-kafka-bridge/pull/49

Releasing bridges 15.1.1 to pre-prod
